### ISSUE TITLE
Remote presses ignored as long as OSD is displayed

### ISSUE THREAD

**Issue by piejanssens** [marcelveldt/xbmc.skin.titan#101]
1. Open TV Guide
2. Select a channel (play) (now the info bar is displayed for x seconds while the video starts playing)
3. Press another button on your remote (switch channel, show channel list, guide, ...)
4. Command is ignored until the info bar leaves the screen

**Comment by mgonzales71** [comment]
I don't have live tv so can't test this.... but just a thought...

try setting skin setting to: 0 (zero) or shorter length of time

![2015-06-22_06-11-11](https://cloud.githubusercontent.com/assets/6510026/8282446/a5a88474-18a5-11e5-903c-5811d79d10c2.png)

**Comment by marcelveldt** [comment]
@piejanssens, this is not a skin issue but it depends on your Kodi remote settings...
I think you have set a custom keyboard.xml ?
You should either set your desired settings at a higher level in the file (in the global section) or make sure you have the same actions set for the fullscreeninfo section and perhaps for the videoosd section too.That keyboard.xml file let's you set the remote control actions overrides for every section in Kodi. So for example you can choose the guide button to be the contextmenu while browsing music, but open the guide when you're watching TV and so on.

Myself I'm just using a plain simple keyboard.xml which has only the global section defined. That way I know that my remote buttons will do the same everywhere in Kodi.

**Comment by piejanssens** [comment]
Ah that's why. Thanks for the explaining here Marcel.
I'll have to reorganize my buttons so I can put everything in global as well.

Btw do you happen to have a button configured so that you can return to the video after showing the full screen EPG while watching TV? When I press return it shows me the left hand menu of the EPG, after that it returns to the home screen with the video playing in the background, after that it returns to the video fullscreen.

**Comment by marcelveldt** [comment]
I believe you can do that by overriding the back button to have the action fullscreenvideo but I'm not 100% sure how to do that.

**Comment by piejanssens** [comment]
And there is nothing in the skin that you can do about this behavior? 
I find it really strange that pressing 'back' causes the side menu to appear...

**Comment by marcelveldt** [comment]
I don't think so, it has something to do with how Kodi handles the windows..
Once you press the guide button it will bring you to the guide window (so it exits the fullscreen video window).

Note that there is also a on screen guide available. This will present the guide on top of the video screen.

**Comment by piejanssens** [comment]
Does the on screen guide have the same layout as the normal guide? The one I tried showed a guide on the left side (like the OSD channel list) and only showed the programs for the channel you are currently watching.

**Comment by marcelveldt** [comment]
no, it's a small sized guide on the left on the screen. You have two of them: one shows the guide for the current channel and the other shows the channelslist.

I will take a look if I can create something custom to show the guide on top of the playing video, maybe this is something I can get done.

**Comment by piejanssens** [comment]
OK muchos gracias :smiley_cat:

**Comment by marcelveldt** [comment]
I tried to fix this but it isn't possible, it's just how Kodi works by default.
