### ISSUE TITLE
sideblade unfocused buttons sometimes not visible

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#107]
sometimes side blade unfocused buttons not visible
(theme color settings?) 

![2015-06-29_18-36-13](https://cloud.githubusercontent.com/assets/6510026/8422251/09084de0-1e8e-11e5-8288-a67ee7f1cc74.jpg)

**Comment by marcelveldt** [comment]
Strange! Any ideas when it happens ?

**Comment by mgonzales71** [comment]
Not yet - but I'm not at a computer right now so I can't confirm what those button labels are using for text and text shadow colors but they don't seem to be using the unfocused button color from the skin settings.

I'll be home in an hour or so I can peek at it more then

**Comment by mgonzales71** [comment]
Sorry I posted comments on this issue in the other side blade issue thread...

I am pretty sure this is the issue:

I think the SubMenuButton include in Includes.xml should look like this:

		<width>458</width>
		<align>left</align>
		<font>Reg26</font>
		<textcolor>$INFO[Skin.String(ButtonTextColor)]</textcolor>
		<focusedcolor>$INFO[Skin.String(ButtonFocusTextColor)]</focusedcolor>
		<shadowcolor>black</shadowcolor>
		<disabledcolor>lightgrey</disabledcolor>
		<invalidcolor>red</invalidcolor>
		<pulseonselect>false</pulseonselect>
		<texturefocus border="5" diffuse="diffuse/panel.png" colordiffuse="$INFO[Skin.String(ButtonFocusColor)]">colors/color_white.png</texturefocus>
		<texturenofocus border="5" diffuse="diffuse/panel_trans.png" colordiffuse="$INFO[Skin.String(ButtonColor)]">colors/color_white.png</texturenofocus>

so the side menu will look like this:

![2015-07-02_18-19-37](https://cloud.githubusercontent.com/assets/6510026/8491006/cddb1dae-20e7-11e5-87c5-82db9dfe4382.png)

and this:

![2015-07-02_18-27-40](https://cloud.githubusercontent.com/assets/6510026/8491022/1c66afa6-20e8-11e5-828b-275015b5e6fb.jpg)

**Comment by mgonzales71** [comment]
what are you thought on making this change?

btw - needed to UPDATE the code above to fix a couple errors.

SubMenuButton include in Includes.xml:

		<width>458</width>
		<align>left</align>
		<font>Reg26</font>
		<textcolor>$INFO[Skin.String(ButtonTextColor)]</textcolor>
		<focusedcolor>$INFO[Skin.String(ButtonFocusTextColor)]</focusedcolor>
		<shadowcolor>black</shadowcolor>
		<disabledcolor>lightgrey</disabledcolor>
		<invalidcolor>red</invalidcolor>
		<pulseonselect>false</pulseonselect>
		<texturefocus colordiffuse="$INFO[Skin.String(ButtonFocusColor)]" border="5">diffuse/panel.png</texturefocus>
        <texturenofocus colordiffuse="$INFO[Skin.String(ButtonColor)]" border="5">diffuse/panel_trans.png</texturenofocus>

the other option if you wanted to leave it as it looks now is to catch the condition where the text color and panel color are the same for the unfocused buttons and handle that exception

for example black text and black panel i think is what causes the original condition.

**Comment by marcelveldt** [comment]
fixed by leaving the submenubutton unoficed color to the general text color.
