### ISSUE TITLE
Q: Auto focus 1st unwatched episode

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#11]
have question about the experimental feature... can you account for sorting of episodes acceding vs descending when jumping to first unwatched?  I sort my episodes so the latest episode should be at the top of the list - but I may have several episodes unwatched - when enabled it never jumps to the first unwatched - only the first item in the list.  hopefully you can read how the list is sorted and jump correctly.  if not - no worries :)  thanks - mario

**Comment by marcelveldt** [comment]
hmm, not sure about that. The current implementation is already a bit of a hack around all kinds of kodi's limitations. What I basically do is programmatically scroll down the list untill I find the first unwatched item...
Will look into it and let you know

**Comment by marcelveldt** [comment]
just thinking... would you still need to sort the episodes by date if you have this new option in the skin ?

**Comment by mgonzales71** [comment]
Yes - because a show may have a season of say 10 shows aired and I am on episode 7.

so the list would be (Episodes sorted descending):

e10 unwatched
e09 unwatched
e08 unwatched  <---- you would want to jump to here
e07 watched
..
e01 watched

No worries - if it is already a hack - adding more complexity would just make it easier to introduce problems.

I can handle scrolling down the list just fine - I was just curious if it was easy to adjust what you had already done to account for when the list its not sorted by default method.

you can close - thanks! :)

**Comment by marcelveldt** [comment]
it was an easy fixed so added it in, also improved thing a bit so now you don't even see it scrolling the list anymore. available in next update.

**Comment by mgonzales71** [comment]
FYI - saw this as an added feature in "Insengard" alpha 2:
"* Add jump to first unwatched in TV section"
so may want to remove this feature for that branch of your skin.

**Comment by marcelveldt** [comment]
That's true.. it was added by one of the titan users :-)
I've disabled the in-skin option for Isengard
