### ISSUE TITLE
sideblade(s) - onup / ondown inconsistent - jumps around in list while scrolling

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#110]
sideblade(s) - onup / ondown inconsistent - jumps around in list while scrolling

noticed in movie & tv show libraries, and various addon sideblade menus.

try scrolling up and down in the various (options) sideblades and you will notice the problem.

note - I have jumped to Isengard beta 2 and have loaded a few contextual addons but I don't think that is the root cause here.

**Comment by marcelveldt** [comment]
In that case it means there's a button with a doubled ID in there somewhere.
Could be in myvideonav.xml or in includesviews.xml --> include sidebladeviewcommands.

All buttons must have a unique ID. Only way to solve is to manually search for the error ;-)

**Comment by mgonzales71** [comment]
Ok...

so there is an issue with the ID and ordering... (the ID's need to be in order and unique correct?)

	<include name="SideBladeViewCommands">
		
		<control type="button" id="612">
			<description>Go to playlist</description>
			<include>SubMenuButton</include>
			<label>13350</label>
			<onclick>$VAR[PlayList]</onclick>
			<visible>[Window.IsActive(videolibrary) + !StringCompare(Playlist.Length(video),0)] | [[Window.IsActive(musiclibrary) | Window.IsActive(musicfiles)] + !StringCompare(Playlist.Length(music),0)]</visible>
		</control>
		
		<control type="radiobutton" id="318">
			<!--show fanart thumb in details pane-->
			<visible>Control.IsVisible(53) | Control.IsVisible(55) | Control.IsVisible(59) | Control.IsVisible(505) | Control.IsVisible(510) | Control.IsVisible(512)</visible>
			<include>SubMenuButton</include>
			<label>31114</label>
			<onclick>Skin.ToggleSetting(DetailsShowFanart)</onclick>
			<selected>Skin.HasSetting(DetailsShowFanart)</selected>
		</control>

		<control type="radiobutton" id="325">
			<!--Show info-->
			<include>SubMenuButton</include>
			<label>36427</label>
			<onclick>Skin.ToggleSetting(FanArtViewShowInfo)</onclick>
			<selected>Skin.HasSetting(FanArtViewShowInfo)</selected>
			<visible>Control.IsVisible(507)</visible>
		</control>
		<control type="radiobutton" id="327">
			<!--Show info-->
			<include>SubMenuButton</include>
			<label>36427</label>
			<onclick>Skin.ToggleSetting(ShowCaseViewShowInfo)</onclick>
			<selected>Skin.HasSetting(ShowCaseViewShowInfo)</selected>
			<visible>Control.IsVisible(500)</visible>
		</control>
		<control type="radiobutton" id="328">
			<!--Show labels-->
			<include>SubMenuButton</include>
			<label>20459</label>
			<onclick>Skin.ToggleSetting(ShowlabelsLandscape)</onclick>
			<selected>Skin.HasSetting(ShowlabelsLandscape)</selected>
			<visible>Control.IsVisible(501) | Control.IsVisible(505) | Control.IsVisible(511) | Control.IsVisible(512)</visible>
			<visible>![container.content(MusicVideos) | Container.Content(tvshows) | Container.Content(Movies) | container.content(seasons)]</visible>
		</control>
		<control type="radiobutton" id="339">
			<!--Show labels-->
			<include>SubMenuButton</include>
			<label>20459</label>
			<onclick>Skin.ToggleSetting(ShowLabelsSquare)</onclick>
			<selected>Skin.HasSetting(ShowLabelsSquare)</selected>
			<visible>Control.IsVisible(509)</visible>
		</control>
		<control type="radiobutton" id="340">
			<!--Show labels-->
			<include>SubMenuButton</include>
			<label>20459</label>
			<onclick>Skin.ToggleSetting(ShowLabelsSquareDetails)</onclick>
			<selected>Skin.HasSetting(ShowLabelsSquareDetails)</selected>
			<visible>Control.IsVisible(510)</visible>
		</control>
		<control type="radiobutton" id="5340">
			<!--Show labels-->
			<include>SubMenuButton</include>
			<label>20459</label>
			<onclick>Skin.ToggleSetting(ShowLabels57)</onclick>
			<selected>Skin.HasSetting(ShowLabels57)</selected>
			<visible>Control.IsVisible(57)</visible>
		</control>
		<control type="radiobutton" id="5341">
			<!--Show labels-->
			<include>SubMenuButton</include>
			<label>20459</label>
			<onclick>Skin.ToggleSetting(ShowLabels52)</onclick>
			<selected>Skin.HasSetting(ShowLabels52)</selected>
			<visible>Control.IsVisible(52)</visible>
		</control>
		<control type="radiobutton" id="5342">
			<!--Show labels-->
			<include>SubMenuButton</include>
			<label>20459</label>
			<onclick>Skin.ToggleSetting(ShowLabels59)</onclick>
			<selected>Skin.HasSetting(ShowLabels59)</selected>
			<visible>Control.IsVisible(59)</visible>
		</control>
		<control type="radiobutton" id="329">
			<!--Show info-->
			<include>SubMenuButton</include>
			<label>36427</label>
			<onclick>Skin.ToggleSetting(PanelViewShowInfo)</onclick>
			<selected>Skin.HasSetting(PanelViewShowInfo)</selected>
			<visible>Control.IsVisible(52)</visible>
		</control>
		<control type="radiobutton" id="335">
			<!--Show info-->
			<include>SubMenuButton</include>
			<label>36427</label>
			<onclick>Skin.ToggleSetting(LandscapeViewShowInfo)</onclick>
			<selected>Skin.HasSetting(LandscapeViewShowInfo)</selected>
			<visible>Control.IsVisible(502)</visible>
		</control>
		<control type="radiobutton" id="701">
			<!--Show info-->
			<include>SubMenuButton</include>
			<label>36427</label>
			<onclick>Skin.ToggleSetting(LogoViewShowInfo)</onclick>
			<selected>Skin.HasSetting(LogoViewShowInfo)</selected>
			<visible>Control.IsVisible(503)</visible>
		</control>
		<control type="radiobutton" id="702">
			<!--Prefer ClearArt-->
			<include>SubMenuButton</include>
			<label>31447</label>
			<onclick>Skin.ToggleSetting(LogoViewPreferClearArt)</onclick>
			<selected>Skin.HasSetting(LogoViewPreferClearArt)</selected>
			<visible>Control.IsVisible(503)</visible>
		</control>
		<control type="radiobutton" id="703">
			<!--fixed position-->
			<include>SubMenuButton</include>
			<label>31511</label>
			<onclick>Skin.ToggleSetting(View52_UseFixedLayout)</onclick>
			<selected>Skin.HasSetting(View52_UseFixedLayout)</selected>
			<visible>Control.IsVisible(52)</visible>
			<onclick>ReloadSkin</onclick>
		</control>
		<control type="radiobutton" id="342">
			<!--Show info-->
			<include>SubMenuButton</include>
			<label>36427</label>
			<onclick>Skin.ToggleSetting(BigListViewShowInfo)</onclick>
			<selected>Skin.HasSetting(BigListViewShowInfo)</selected>
			<visible>Control.IsVisible(51)</visible>
		</control>
		
		<control type="radiobutton" id="1342">
			<!--Show info-->
			<include>SubMenuButton</include>
			<label>36427</label>
			<onclick>Skin.ToggleSetting(SlimListViewShowInfo)</onclick>
			<selected>Skin.HasSetting(SlimListViewShowInfo)</selected>
			<visible>Control.IsVisible(516)</visible>
		</control>
		
		<control type="radiobutton" id="343">
			<!--Hide panel behind moviedetails-->
			<include>SubMenuButton</include>
			<label>31155</label>
			<onclick>Skin.ToggleSetting(DetailsLeftHidepanel)</onclick>
			<selected>Skin.HasSetting(DetailsLeftHidepanel)</selected>
			<visible>Control.IsVisible(53) | Control.IsVisible(55) | Control.IsVisible(59) | Control.IsVisible(505) | Control.IsVisible(510) | Control.IsVisible(512)</visible>
		</control>
		<control type="radiobutton" id="330">
			<!--Show discart-->
			<include>SubMenuButton</include>
			<label>31200</label>
			<onclick>Skin.ToggleSetting(View58_ShowCDart)</onclick>
			<selected>Skin.HasSetting(View58_ShowCDart)</selected>
			<visible>Control.IsVisible(58)</visible>
		</control>
		<control type="radiobutton" id="331">
			<!--Show discart-->
			<include>SubMenuButton</include>
			<label>31200</label>
			<onclick>Skin.ToggleSetting(View508_ShowCDart)</onclick>
			<selected>Skin.HasSetting(View508_ShowCDart)</selected>
			<visible>Control.IsVisible(508)</visible>
		</control>
		<control type="radiobutton" id="332">
			<!--Show discart-->
			<include>SubMenuButton</include>
			<label>31200</label>
			<onclick>Skin.ToggleSetting(View513_ShowCDart)</onclick>
			<selected>Skin.HasSetting(View513_ShowCDart)</selected>
			<visible>Control.IsVisible(513)</visible>
		</control>
		<control type="radiobutton" id="333">
			<!--Show discart-->
			<include>SubMenuButton</include>
			<label>31200</label>
			<onclick>Skin.ToggleSetting(View514_ShowCDart)</onclick>
			<selected>Skin.HasSetting(View514_ShowCDart)</selected>
			<visible>Control.IsVisible(514)</visible>
		</control>
		<control type="radiobutton" id="334">
			<!--Show discart-->
			<include>SubMenuButton</include>
			<label>31200</label>
			<onclick>Skin.ToggleSetting(View52_ShowCDart)</onclick>
			<selected>Skin.HasSetting(View52_ShowCDart)</selected>
			<visible>Control.IsVisible(52)</visible>
		</control>
		<control type="radiobutton" id="336">
			<!--Show discart-->
			<include>SubMenuButton</include>
			<label>31200</label>
			<onclick>Skin.ToggleSetting(View502_ShowCDart)</onclick>
			<selected>Skin.HasSetting(View502_ShowCDart)</selected>
			<visible>Control.IsVisible(502)</visible>
		</control>
		<control type="radiobutton" id="344">
			<!--Show discart-->
			<include>SubMenuButton</include>
			<label>31200</label>
			<onclick>Skin.ToggleSetting(View51_ShowCDart)</onclick>
			<selected>Skin.HasSetting(View51_ShowCDart)</selected>
			<visible>Control.IsVisible(51)</visible>
		</control>
		<control type="radiobutton" id="345">
			<!--animate discart-->
			<include>SubMenuButton</include>
			<label>31201</label>
			<onclick>Skin.ToggleSetting(AnimateDiscArt)</onclick>
			<selected>Skin.HasSetting(AnimateDiscArt)</selected>
			<visible>
			[Skin.HasSetting(View58_ShowCDart) + Control.IsVisible(58)] | 
			[Skin.HasSetting(View508_ShowCDart) + Control.IsVisible(508)] | 
			[Skin.HasSetting(View513_ShowCDart) + Control.IsVisible(513)] | 
			[Skin.HasSetting(View514_ShowCDart) + Control.IsVisible(514)] | 
			[Skin.HasSetting(View51_ShowCDart) + Control.IsVisible(51)] | 
			[Skin.HasSetting(View52_ShowCDart) + Control.IsVisible(52)]
			</visible>
			<visible></visible>
		</control>
		<control type="radiobutton" id="1501">
			<!--Hide background panel-->
			<include>SubMenuButton</include>
			<label>31155</label>
			<onclick>Skin.ToggleSetting(View51_HidePanel)</onclick>
			<selected>Skin.HasSetting(View51_HidePanel)</selected>
			<visible>Control.IsVisible(51) + !StringCompare(Skin.String(ViewDetailsPanelOpacity),0)</visible>
		</control>
		<control type="radiobutton" id="1502">
			<!--Hide background panel-->
			<include>SubMenuButton</include>
			<label>31155</label>
			<onclick>Skin.ToggleSetting(View515_HidePanel)</onclick>
			<selected>Skin.HasSetting(View515_HidePanel)</selected>
			<visible>Control.IsVisible(515) + !StringCompare(Skin.String(ViewDetailsPanelOpacity),0)</visible>
		</control>
		<control type="radiobutton" id="1503">
			<!--Hide background panel-->
			<include>SubMenuButton</include>
			<label>31155</label>
			<onclick>Skin.ToggleSetting(View516_HidePanel)</onclick>
			<selected>Skin.HasSetting(View516_HidePanel)</selected>
			<visible>Control.IsVisible(516) + !StringCompare(Skin.String(ViewDetailsPanelOpacity),0)</visible>
		</control>
		
		<control type="radiobutton" id="1504">
			<!--use slim list-->
			<include>SubMenuButton</include>
			<label>31453</label>
			<onclick>Skin.ToggleSetting(View51_UseSlimList)</onclick>
			<selected>Skin.HasSetting(View51_UseSlimList)</selected>
			<visible>Control.IsVisible(51)</visible>
			<visible>![Container.content(tvshows) + Skin.HasSetting(ListViewShowBanners)]</visible>
		</control>
		
		<control type="radiobutton" id="1505">
			<!--use slim list-->
			<include>SubMenuButton</include>
			<label>31453</label>
			<onclick>Skin.ToggleSetting(View515_UseSlimList)</onclick>
			<selected>Skin.HasSetting(View515_UseSlimList)</selected>
			<visible>Control.IsVisible(515)</visible>
			<visible>![Container.content(tvshows) + Skin.HasSetting(ListViewShowBanners)]</visible>
		</control>
		
		<control type="radiobutton" id="1506">
			<!--use banners for tv shows-->
			<include>SubMenuButton</include>
			<label>31454</label>
			<onclick>Skin.ToggleSetting(ListViewShowBanners)</onclick>
			<selected>Skin.HasSetting(ListViewShowBanners)</selected>
			<visible>Control.IsVisible(515) | Control.IsVisible(51) | Control.IsVisible(50)</visible>
			<visible>Container.content(tvshows)</visible>
		</control>
		
		<control type="radiobutton" id="601">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View50_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View50_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(50)</visible>
		</control>
		<control type="radiobutton" id="602">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View51_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View51_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(51)</visible>
		</control>
		<control type="radiobutton" id="603">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View52_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View52_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(52)</visible>
		</control>
		<control type="radiobutton" id="604">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View53_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View53_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(53)</visible>
		</control>
		<control type="radiobutton" id="605">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View54_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View54_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(54)</visible>
		</control>
		<control type="radiobutton" id="606">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View55_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View55_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(55)</visible>
		</control>
		<control type="radiobutton" id="607">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View56_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View56_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(56)</visible>
		</control>
		<control type="radiobutton" id="608">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View57_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View57_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(57)</visible>
		</control>
		<control type="radiobutton" id="609">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View58_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View58_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(58)</visible>
		</control>
		<control type="radiobutton" id="610">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View59_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View59_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(59)</visible>
		</control>
		<control type="radiobutton" id="611">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View500_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View500_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(500)</visible>
		</control>
		<control type="radiobutton" id="612">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View501_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View501_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(501)</visible>
		</control>
		<control type="radiobutton" id="613">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View502_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View502_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(502)</visible>
		</control>
		<control type="radiobutton" id="614">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View505_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View505_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(505)</visible>
		</control>
		<control type="radiobutton" id="615">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View506_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View506_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(506)</visible>
		</control>
		<control type="radiobutton" id="616">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View507_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View507_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(507)</visible>
		</control>
		<control type="radiobutton" id="617">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View508_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View508_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(508)</visible>
		</control>
		<control type="radiobutton" id="618">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View509_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View509_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(509)</visible>
		</control>
		<control type="radiobutton" id="619">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View510_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View510_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(510)</visible>
		</control>
		<control type="radiobutton" id="620">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View511_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View511_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(511)</visible>
		</control>
		<control type="radiobutton" id="621">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View512_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View512_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(512)</visible>
		</control>
		<control type="radiobutton" id="622">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View513_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View513_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(513)</visible>
		</control>
		<control type="radiobutton" id="623">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View514_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View514_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(514)</visible>
		</control>
		<control type="radiobutton" id="624">
			<!--Disable fanart-->
			<include>SubMenuButton</include>
			<label>31268</label>
			<onclick>Skin.ToggleSetting(View515_DisableFanArt)</onclick>
			<selected>Skin.HasSetting(View515_DisableFanArt)</selected>
			<visible>Skin.HasSetting(ShowFanartBackground)</visible>
			<visible>Control.IsVisible(515)</visible>
		</control>

	</include>

**Comment by mgonzales71** [comment]
I notice all the buttons have the include: SubMenuButton

   
    <include name="SubMenuButton">
        
        <width>458</width>
        <align>left</align>
		<font>Reg26</font>
        <textcolor>$INFO[Skin.String(FooterTextColor)]</textcolor>
        <disabledcolor>77585858</disabledcolor>
        <pulseonselect>false</pulseonselect>
        <texturefocus colordiffuse="$INFO[Skin.String(ButtonFocusColor)]">colors/color_white.png</texturefocus>
        <texturenofocus>-</texturenofocus>
		
    </include>

**Comment by mgonzales71** [comment]
should it be something more like:

 <include name="SubMenuButton">
        <width>458</width>
        <align>left</align>
	<font>Reg26</font>
        <textcolor>$INFO[Skin.String(ButtonTextColor)]</textcolor>
        <focusedcolor>$INFO[Skin.String(ButtonFocusTextColor)]</focusedcolor>
	<shadowcolor>black</shadowcolor>
        <disabledcolor>lightgrey</disabledcolor>
        <invalidcolor>red</invalidcolor>
        <pulseonselect>false</pulseonselect>
        <texturefocus colordiffuse="$INFO[Skin.String(ButtonFocusColor)]">diffuse/panel.png</texturefocus>
        <texturenofocus colordiffuse="$INFO[Skin.String(ButtonColor)]">diffuse/panel_trans.png</texturenofocus>		
    </include>

**Comment by mgonzales71** [comment]
those changes produce this:

![2015-07-02_18-19-37](https://cloud.githubusercontent.com/assets/6510026/8490961/f87ec55c-20e6-11e5-8905-42ddf46ef93e.png)

I guess it's your call on what to change them to... if you agree with what I think - copy and paste or I can do a PR with the changes.

still need to look at the scrolling issue (jumping in the list)

**Comment by marcelveldt** [comment]
The ID's do not need to be in a specific order, as long as they're unique it's okay.
All ID's in the entire active window should be unique and note that some ID's are reserved by Kodi. Basically it's just a matter of some trial and error :-)

**Comment by mgonzales71** [comment]
ok - i thought I had read that they needed to be in order if you didn't use explicit onup/ondown, etc.

Q -  can you use a button ID in a dialog say - 3011 for skin settings, but then in another dialog that's unrelated - for example a search dialog use 3011 again?

I will have to see if I can find the culprit - most the side and context menus a jumping now lol

**Comment by marcelveldt** [comment]
Well, if you have the Id's in order it's a bit better to read (and find errors). But some Id's are system defined, like in the video sideblade. Mostly I just make up some random ID that's pretty high to prevent conflicts with system defined Id's for any buttons/controls that I add myself.

Yes, you can use an ID that's used somewhere else as long as it isn't used in the active window (by includes for example).

Note that for myvideonav.xml some of the sideblade buttons are defined in the windows xml itself and some are defined in the include "sidebladeviewcommands" or something like that

**Comment by mgonzales71** [comment]
ok thanks for clearing that up :)   

oh wait - let me try that skin tool and see if it can catch the issue :)

**Comment by mgonzales71** [comment]
nope that tool wasn't any help - it was worth a quick try - it has a "check ID" feature but really didn't squak about anything.

**Comment by mgonzales71** [comment]
Ok - I think it's the disable fanart that is causing the problem - It's the item that seems to trigger the jumping around - I can't find where it actually is in the xml files.

Also - what did you think about the issue with the buttons in the side blade?  should they adopt the theme colors or take in account when the text and panel colors are the same?  (that makes the non-focused buttons invisible)

**Comment by marcelveldt** [comment]
just fixed the issue with the sideblade menu Id's.
also merged your change with the colorsettings for sideblade buttons with one additional change that I change the button unfocused color to empty because it didn't look very well with those buttons on the sideblade canvas.

**Comment by mgonzales71** [comment]
If you leave out the unfocused button color how did you address the issue of the unfocused text color & blade panel color being the same resulting in invisible buttons? 

That was the dilemma that caused me to look into this change.

I guess I figured that If the user wanted invisible unfocused buttons that they could basically set the theme colors themselves and get what you were actually doing by default in the skin?

Then I thought about maybe using variable statement but that would then keep people from setting it "wrong" by again forcing the behavior in the skin.

It's a tough call - do you give the color theme customization to the user and let them make the "wrong" choices? OR do you have the skin impose certain theme elements that are not customizable while the rest are?

The other option is to have a panel color setting for the side blades in the skin settings?

You can go crazy thinking about all this :-)
