### ISSUE TITLE
new icons / fanart

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#114]
made some new icons - i can change text, etc easily - added the emby logo since you support it (media browser).  I can remove / move the logo, etc easily as well.

![titan skin icon](https://cloud.githubusercontent.com/assets/6510026/8532246/98848b8e-23e1-11e5-9dc2-66478fa172f9.png)

alternate skin icon...

![titan skin icon](https://cloud.githubusercontent.com/assets/6510026/8539020/c6c1bf50-242a-11e5-8afb-b53d1eabb941.png)

skin helper icon...

![titan skin helper script icon](https://cloud.githubusercontent.com/assets/6510026/8532243/9171019c-23e1-11e5-813a-304efea35371.png)

**Comment by mgonzales71** [comment]
in case you wanted a matching splash screen.... again i can change text, move stuff around easily.
I kept the pdn file with all the elements as layers so it's easy to move/change things around.

![titan splash](https://cloud.githubusercontent.com/assets/6510026/8533659/5a988a14-23eb-11e5-98b7-43875d3b5baf.png)

**Comment by mgonzales71** [comment]
and why not... new fan art.. tried to showcase the various skin setups available in the skin.

![titan fanart](https://cloud.githubusercontent.com/assets/6510026/8535745/a863e466-23fd-11e5-865f-f4f410e7b943.jpg)

**Comment by mgonzales71** [comment]
just to give you options alternative fanart.... with various darkened overlays to subdue the image a bit if desired.

![titan fanart 2](https://cloud.githubusercontent.com/assets/6510026/8536174/5a8dc4c8-2402-11e5-8285-2b059706fc23.jpg)

![titan fanart 3](https://cloud.githubusercontent.com/assets/6510026/8536175/5a8e1d4c-2402-11e5-82af-f64cfa38634a.jpg)

![titan fanart 4](https://cloud.githubusercontent.com/assets/6510026/8536172/5a6ac158-2402-11e5-89c4-6377cd613059.jpg)

**Comment by mgonzales71** [comment]
ok so I got a little bored so threw together a couple more variations for fanart  :smile:

![titan fanart5](https://cloud.githubusercontent.com/assets/6510026/8538936/9a86e3a8-2429-11e5-9d9d-c0ea82c90d74.jpg)

![titan fanart6](https://cloud.githubusercontent.com/assets/6510026/8538937/9a86e8b2-2429-11e5-91a5-93d5cfd92055.jpg)

**Comment by marcelveldt** [comment]
Hey Mario,

The logo: please leave the Emby logo and make text less bold That way is looks much sharper.

As for the fanart. Nice suggestion about the fanart but I'd rather see the plain blue background with the logo and Kodi logo.

Can you make the fanart high-res 720 or 1080p without it being a superlarge file ?

**Comment by mgonzales71** [comment]
ok - think I understand what you want.
and can do all that.

did you want the splash screen to be as is but with less bold txt as well?

I will redo and post updates in a few :smile:

**Comment by mgonzales71** [comment]
This how you wanted the icons?

![titan skin icon](https://cloud.githubusercontent.com/assets/6510026/8560453/bdb315f6-24cc-11e5-9be4-8ce1fd4f4594.png)
![titan skin helper icon](https://cloud.githubusercontent.com/assets/6510026/8560452/bdb172aa-24cc-11e5-8758-9c458904f440.png)

**Comment by mgonzales71** [comment]
and i think this is what you wanted for splashscreen

![titan splashscreen](https://cloud.githubusercontent.com/assets/6510026/8560719/c65b8fe6-24cf-11e5-80ce-52ddab20e3e1.jpg)

and fanart

![titan fanart](https://cloud.githubusercontent.com/assets/6510026/8560722/cda6428c-24cf-11e5-9c3c-2dc2b0150be7.jpg)

**Comment by mgonzales71** [comment]
I can run the last 4 files thru tinyjpg.com and tinypng.com and get about 40% reduction in size but quality will go down some as well.

if they are small enough we can leave as is -- right now they are like 50k and 75k for the jpg's and 3k per icon.

**Comment by mgonzales71** [comment]
oops... I just read that the fanart you wanted the kodi log as well... or is this ok?  no trouble to add it.

**Comment by marcelveldt** [comment]
Hey Mario,

fanart is great as-is. Please make the quality as best as possible without getting a very huge file.
Problem with the current fanart and splashscreen is that i's a bit bad quality which some users already complained about.

About the logo and splash-screen... Can you leave the emby logo out ?
I think it looks more clean without it.

**Comment by mgonzales71** [comment]
Ok I will clean up the fanart in the style it is now.

Sound like with splashscreen you want to:
- drop emby logo
- "Titan" text is ok
- will clean up Titan logo itself 
- keep Kodi logo? (Kodi name with Kodi icon, just Kodi icon, ?)

Both Icons are good and should be done unless you want any changes right?

I Can do this in the morning - looks
you're 9 hours ahead ( I'm off to bed for now :-) 

Till then have a great morning, day!

**Comment by marcelveldt** [comment]
Yes indeed, that's what I meant. Keep the Kodi logo like it was, the name belongs to the logo.
Thanks!

And yes, it's 11 AM in the morning here :-) 
Good night!

**Comment by mgonzales71** [comment]
I ended up helping my dad paint all day (I now hate to paint! LOL) so tonight I can do the final clean up and then I can create a PR for you. :smile:

**Comment by mgonzales71** [comment]
ok - think I have it all as you wanted... if so here is the PR

https://github.com/marcelveldt/xbmc.skin.titan/pull/116

**Comment by marcelveldt** [comment]
Hi Mario, very nice thank you.
Just one thing: Can you remove the emby logo from the skin logo ? It doesn't fit very well in the logo. Just the plain Titan logo with text is enough.
End result is very elegant !

**Comment by mgonzales71** [comment]
updated PR with changes:

![titan skin helper icon](https://cloud.githubusercontent.com/assets/6510026/8627199/3bee2176-26fe-11e5-9f72-4d3da1d0a16f.png)
![titan skin icon](https://cloud.githubusercontent.com/assets/6510026/8627200/3bf074d0-26fe-11e5-9d4b-a769ccb84500.png)

**Comment by marcelveldt** [comment]
Hi Mario, just tested the new icons and fanart in the skin. Looking good, thanks for your work!

Just one little detail: On the splash screen the titan+kodi logo are a bit large... I think they're abit too overwhelming maybe. Possible to make them a bit smaller on the splash screen ?

**Comment by mgonzales71** [comment]
ok - I can make them smaller if you like - by what percentage would you like them reduced?

I also forgot the fanart for UI sounds so I just created a PR for that - I can make the changes to the splashscreen and add to that PR.

**Comment by marcelveldt** [comment]
Well, I think they can be a whole lot smaller in the splashscreen... something like 50% reduce or so ?

**Comment by mgonzales71** [comment]
I took a stab at it before your reply.

how is this?

I added it to the PR in the hopes you like :)

![splashscreen](https://cloud.githubusercontent.com/assets/6510026/8631494/4fb43302-272c-11e5-825a-ee3bde4d2115.jpg)

**Comment by marcelveldt** [comment]
I like! Much better now. Great stuff!

Just in time for tonight's new beta. Seems to be a problem with the helper script reported by users which I can't reproduce. Hopefully I just fixed it.

If no issues come across tomorrow I'll go for the release to stable :-)

**Comment by mgonzales71** [comment]
you're welcome Marcel - glad you like.
I will have to catch up on the forums to see what problems folks are having - I haven't seen anything myself that is obvious.
