### ISSUE TITLE
customize skin shortcuts - menus swapped?

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#121]
hard to explain but I was customizing the power menu and when I choose Settings under choose shortcut I get --- Favorites.

if I choose Favorites ---- I get Addons

they appear to not going where the menu label would indicate.

![2015-07-13_03-32-49](https://cloud.githubusercontent.com/assets/6510026/8647851/819b257a-2910-11e5-8132-c951117f3f2c.png)

**Comment by mgonzales71** [comment]
Actually Choosing Favorites gives you Add-on...
![2015-07-13_03-40-03](https://cloud.githubusercontent.com/assets/6510026/8647893/ea68bf9a-2910-11e5-8c1f-cda14e1fcf7c.png)

**Comment by mgonzales71** [comment]
Choosing Addon - gives you Pictures shortcut choices.

I haven't checked them all - so there may be others..

**Comment by marcelveldt** [comment]
thanks for the catch, just fixed.
