### ISSUE TITLE
cosmetic issue: missing unwatched idicators / season fanart

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#13]
on some views - the unwatched indicator is missing / not consistent with other views:

http://i.imgur.com/iwpiWn9.jpg
http://i.imgur.com/oCKPrxZ.jpg
http://i.imgur.com/l18gHDK.jpg
http://i.imgur.com/aqRSvse.jpg
http://i.imgur.com/BQS3fnz.jpg
http://i.imgur.com/wbxAc8M.jpg

Also all but 1 or 2 views no longer show season fanart.

**Comment by marcelveldt** [comment]
this is all fixed in latest update
