### ISSUE TITLE
minor cosmetic issue: all add-on configure dialogs have fixed control colors

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#14]
seems all the controls in the add-on configure dialogs are fixed to the color green/lime - hehe :)

I rather like both yellow, the default blue and lime focus colors personally - can't decide which to stay with!

![chsdyxo 1](https://cloud.githubusercontent.com/assets/6510026/6283938/a3f6d984-b89f-11e4-8ad4-8120a41205bf.png)

**Comment by marcelveldt** [comment]
thanks for the catch, just fixed it!
