### ISSUE TITLE
bug: yahoo weather display

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#15]
when yahoo is weather provider main conditions icon is missing and I am not sure if yahoo provides 5+ day, hourly, etc forecasts or not but the menu seems to be missing as well.

![4gn7t68 1](https://cloud.githubusercontent.com/assets/6510026/6313361/0854e108-b95b-11e4-9bec-57c7dc1c7d5b.png)

**Comment by marcelveldt** [comment]
fixed the issue with the icon for the basic weather screen.
Yahoo only provides basic weather info (daily forecast)...
Only if the weather provider does provide the extended info it will show the extended weather panel, otherwise it'll fallback to the simple one.
