### ISSUE TITLE
FR: restyle volume graphics

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/xbmc.skin.titan#21]
the volume grahpic and mute icon is a bit outdated... update to more modern approach (for default theme)

**Comment by mgonzales71** [comment]
what direction where you thinking?
let me know if I can help.

**Comment by mgonzales71** [comment]
some quick ideas for you to ponder....

![vol-proto1](https://cloud.githubusercontent.com/assets/6510026/6656563/2ff5e36e-caeb-11e4-91b6-f69012b30056.png)

maybe something like the progress dialog?
![unnamed](https://cloud.githubusercontent.com/assets/6510026/6656597/91be12ec-caeb-11e4-9f1b-a238439ee187.png)
 - colorized?

can make into segments based on percentage?

or just simple icons with a linear progress bar as it has now?

![volume indicators - simple](https://cloud.githubusercontent.com/assets/6510026/6656644/068c97aa-caed-11e4-8715-b048bbd55616.png)

**Comment by mgonzales71** [comment]
https://dl.dropboxusercontent.com/u/2203431/some%20ideas.zip

put these images and few others i was playing with in a zip for ya to look at and use or modify if you want.

enjoy! :)

M

**Comment by mgonzales71** [comment]
ok so I got bored last night and played around with volume graphics and code to use them,

the graphics are not as crisp as i would like for a final version at 200x200 pixels - but it looks  better at 100x100 (size before I doubled the main volume control... left mute at 100x100).

but if you want to check it out...

have 2 mods

one with color progress and another grey_scale that follow button focus color 

i am sure I made some coding mistakes but seems to work as far as I can tell.

actually - I like the way the Bello skin displays the main volume control progress.... (but I would rather have a percent/% instead of dB) and I don't like Bello's mute graphics.

check it out if you haven't already.

Mario

https://dl.dropboxusercontent.com/u/2203431/volume%20mod.zip

**Comment by mgonzales71** [comment]
screenshots of mute indicator, 100% and 37% volume (color progress)

http://i.imgur.com/I71RMAl.jpg
http://i.imgur.com/d4U918v.jpg
http://i.imgur.com/GwatJob.jpg

**Comment by mgonzales71** [comment]
hope you like - pushed a few changes - been testing last couple days without any problems.  revert if you don't like.

**Comment by marcelveldt** [comment]
Hey Mario, sorry for the late response.. I've been busy a bit with another project at the MediaBrowser side.. Is about to get released for beta so I'll have some more time again for the skin.

Thanks for your contributions. I just looked at the screenshots and the images are not so sharp, or is that just the screenshot ? The rounded adges do not fit the sharp edges of the overall default theme. For classic I'd say they're perfect but not for the default theme.

This is what I'm thinking about:

A small panel, can be the same as all panels used in the skin like the footer etc.
In the panel a shard/modern white PNG image of the volume icon...
This panel with icon slides from the side... I think I've seen this in some other skin but I'm not sure. 1080XF perhaps ?

**Comment by marcelveldt** [comment]
https://cloud.githubusercontent.com/assets/6510026/6656597/91be12ec-caeb-11e4-9f1b-a238439ee187.png

that one I like ! So basically just like the progress bar but than on a panel that matches the rest of the skin...

Take a look at myvideonav.xml and look for the "scrolling letter panel". That's what we can use and than make it a bit bigger offcourse

**Comment by mgonzales71** [comment]
![mute-demo](https://cloud.githubusercontent.com/assets/6510026/6721572/b73c8f92-cd8b-11e4-9862-0c4940e9ea76.png)
![vol-demo](https://cloud.githubusercontent.com/assets/6510026/6721571/b73b5b54-cd8b-11e4-8336-2877fe0f32d8.png)

how does that look?

https://dl.dropboxusercontent.com/u/2203431/new-volume-mute.zip

zip of the individual graphic elements - if you like I can make individual segment files to use in a progress bar

**Comment by mgonzales71** [comment]
final submission :)

32 segment progress "bar" images

Not sure how to write code for a range (ie volume level 1-3 = image 1, etc)

demo images over a picture - images are now crisp and clean

![full-vol-demo](https://cloud.githubusercontent.com/assets/6510026/6722840/5c52df48-cd9d-11e4-9529-b2ee9cd8b796.png)
![mute-demo](https://cloud.githubusercontent.com/assets/6510026/6722839/5c52d746-cd9d-11e4-98ee-2dc15acf18f6.png)
![partial-vol-demo](https://cloud.githubusercontent.com/assets/6510026/6722838/5c5022e4-cd9d-11e4-83d1-c1b44ff41a6d.png)

zip of hopefully final media.

https://dl.dropboxusercontent.com/u/2203431/new-volume-mute%20%28final%29.zip

hope you like what I have done 

Thanks

mario

**Comment by mgonzales71** [comment]
figured out the code!!! :-)

pics of code in action in my copy of the skin... ready to commit if you like.

let me know.

thanks Marcel!

Mario

![2015-03-18_22-41-52](https://cloud.githubusercontent.com/assets/6510026/6725094/e51fe082-cdc0-11e4-8acb-f903b81e12cd.jpg)
![2015-03-18_22-42-09](https://cloud.githubusercontent.com/assets/6510026/6725095/e51fcab6-cdc0-11e4-94cd-e6ae2b76a656.jpg)
![2015-03-18_22-42-25](https://cloud.githubusercontent.com/assets/6510026/6725093/e51e2ef4-cdc0-11e4-9c1c-10ec77b47182.jpg)

**Comment by mgonzales71** [comment]
All done - I re-read what you wanted and I figured out all the code hehe :)

hope you like!

Clean & Modern look

same size as previous vol controls 
380x380 pixels

back panel follows - $VAR[panel_color]
my setting - BLACK 

opacity follows - OSDPanelOpacity
my setting - 40%

segment color follows - button focus color
my setting - YELLOW


code and images

https://dl.dropboxusercontent.com/u/2203431/titan%20volume-mute%20mods.zip

final screen shots:

![2015-03-19_03-15-33](https://cloud.githubusercontent.com/assets/6510026/6728374/a61f16c0-cde6-11e4-8420-eaa7733b8768.jpg)

![2015-03-19_03-15-51](https://cloud.githubusercontent.com/assets/6510026/6728373/a61ef3c0-cde6-11e4-94bf-b869783199cd.jpg)

Center control briefly display large mute icon when vol level reaches 0

![2015-03-19_03-17-34](https://cloud.githubusercontent.com/assets/6510026/6728375/a61fac20-cde6-11e4-821f-1b232d1e5fbe.jpg)

persistent mute indicator in upper right corner

![2015-03-19_03-17-02](https://cloud.githubusercontent.com/assets/6510026/6728372/a61ea136-cde6-11e4-831a-4562d16803c6.jpg)

**Comment by marcelveldt** [comment]
changes are committed to the skin and looking great. Thanks Mario!
