### ISSUE TITLE
FYI: updated background overlays

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#25]
take at look at the bigred, darkblue, frost and grey background overlays... you may want to consider reverting them or retrying the image optimization  - they no longer work effectively as an image overlay.  (missing or severely reduced opacity/alpha channels)

![2015-03-19_21-14-18](https://cloud.githubusercontent.com/assets/6510026/6745958/1116fb28-ce7d-11e4-929e-bbe11dfcd26a.png)

**Comment by marcelveldt** [comment]
Oops, I didn't notice that.. will revert it right away.
Thanks for the catch!
