### ISSUE TITLE
suggestion: replace use of common\button-nf.png with....

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#26]
texture of: light opacity button focus color   OR  darker opacity of the currently set panel color maybe? 

for example:

the old non-focus button texture:- the remaining buttons sort of look like orphans now in the in skin.

![button-nf](https://cloud.githubusercontent.com/assets/6510026/6763939/e27a686e-cf52-11e4-8387-cb5d4fe0cc99.png)

could be replaced with maybe one of the following through out the skin...?

demo of a couple of ideas:

![2015-03-20_22-41-08](https://cloud.githubusercontent.com/assets/6510026/6763944/3a55d69a-cf53-11e4-88ef-ac5f21fd8ec0.png)

another idea

![2015-03-20_22-30-40](https://cloud.githubusercontent.com/assets/6510026/6763945/3a584470-cf53-11e4-9016-938a27625659.png)

code I used in demo in place of the static texture image....

<texture>colors/color_white.png</texture>
<colordiffuse>$INFO[Skin.String(ButtonFocusColor)]</colordiffuse>
<animation effect="fade" reversible="false" end="20" time="0" condition="true">Conditional</animation>

what do you think?

**Comment by marcelveldt** [comment]
Hey Mario, great suggestion! Can you send me the PR with github for this change so I can merge it in ?

**Comment by mgonzales71** [comment]
Oh.... I had only modified settings.xml as a test/demo... 

but I can work on updating them and the do a PR.

which example did you like?  or other ideas did you have along that same thought?

also - 

Q - for the setting description the text is "grey" - I couldn't find where to change that to a more readable color.- where is that color being set?

thanks!

**Comment by mgonzales71** [comment]
created a pull request with changes.  please review and merge if you approve.

thanks - mario

**Comment by marcelveldt** [comment]
changes merged into the skin, looking great!
