### ISSUE TITLE
TexturePacker updated

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#27]
http://kodi.wiki/view/TexturePacker

Just an FYI: 

TexturePacker 1.0.2 is out - it's now a single executable (finally!) and fixes several issues with image and dup image handling..

download link if interested in migrating your build process to the new binary:

http://mirrors.kodi.tv/build-deps//win32/texturepacker-1.0.2-win32.7z

I've been using it for a week without any issues now.

v1.0.1 had a crashing issue that is now fixed.

enjoy!

mario

**Comment by marcelveldt** [comment]
Thanks, I've updated the texturepacker on the skin's git
