### ISSUE TITLE
Trakt - Titan Skin 

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#33]
Started work on trying to figure out how to skin the trakt dialog and context menu in the theme of titan skin.

I got some of it figured out but I think the scaling is off because I was taking code for 720p and trying to make it work with 1080i.

I kept messing up trying to scale it properly - right now it looks too small in scale to what it should look.

Also - I am sure you would want to have a little different look for the classic theme.

Here is what I got so far....

https://dl.dropboxusercontent.com/u/2203431/trakt-titan-skin.zip

hopefully some of this is useful to you.  if not, sorry.. :)

obviously you can just leave trakt as it - just was hoping to help out some more if I could!

Maybe I can work on it again in a day or two and see if I can get it looking better.  hehe

![screenshot002](https://cloud.githubusercontent.com/assets/6510026/6989028/c890c92a-da0b-11e4-87ee-90038104f2ab.png)
![screenshot003](https://cloud.githubusercontent.com/assets/6510026/6989029/c891c1d6-da0b-11e4-83c4-a6a8d55f0df0.png)

**Comment by mgonzales71** [comment]
tweaked the code a little more - and have the ratings dialog looking a lot better and right sized still having a hard time getting the context menu dialog to be a little bit larger - it seems to have a mind of it's own :-)
xml files in previous linked zip have been updated

new screenshots 

![2015-04-04_18-10-22](https://cloud.githubusercontent.com/assets/6510026/6995346/373f41c2-daf6-11e4-86d5-8fa6bd524ebe.jpg)

![2015-04-04_18-03-41](https://cloud.githubusercontent.com/assets/6510026/6995347/37400080-daf6-11e4-848b-4b6a40052893.jpg)

**Comment by mgonzales71** [comment]
oh and oddly enough - the latest script.trakt (Git dev copy) renders the same exact xml files slightly differently (for the better actually) - in case you wanted to grab it here is the link - https://github.com/Razzeee/script.trakt/tree/dev they must have fixed a cosmetic related bug.

cheers!

mario

**Comment by marcelveldt** [comment]
hey mario, can you do a pull request with these changes ? I can then merge them into the skin.

Thanks again for participating!

**Comment by mgonzales71** [comment]
here you go sir! - hope you like 

https://github.com/marcelveldt/xbmc.skin.titan/pull/34

Glad to help

Mario

**Comment by marcelveldt** [comment]
Thanks Mario!
