### ISSUE TITLE
FR - With OSD menu only cycle subtitles with 'Next' don't disable at the end

### ISSUE THREAD

**Issue by piejanssens** [marcelveldt/xbmc.skin.titan#35]
It's annoying if you are pressing the 'Next' button of the OSD subtitle menu when suddenly you disable the subs because your reached the end of the subtitles and pressed next. There is a seperate enable/disable button for that, 'Next' should only cycle the subs not disable them. The cycle+disable combo was introduced to make it easier on remotes, but was never meant to be used as such in the menu.

**Comment by marcelveldt** [comment]
Do you by any chance have the name of the command for that "cycle only" button ? I've searched through the documentation but couldn't find it.

**Comment by marcelveldt** [comment]
BTW: the current command is this: NextSubtitle

**Comment by piejanssens** [comment]
You are right, there is no command to do cycle only.
In that case the menu controls/logic should be altered.
A quick fix would be to make the enable button active after cycling over the last subs when subs get disabled. Currently one of the buttons (I think the pause button) in the OSD menu itself gets active and the subtitle sub menu is still shown. So cycling through the subs quickly makes you pause the movie accidentally. Better would be to make the 'Enable' button of the subtitle sub menu active. This way you can keep pressing Enter/OK and it will go from sub1/sub2/sub3/../disabled/enabled-sub1/sub2/...

**Comment by marcelveldt** [comment]
OK, I think I fixed this. The button will now toggle between next subtitles and when those are disabled it can be used to enable the subtitles. Available in tonight's next beta of the skin.
Thanks for the feedback!

**Comment by piejanssens** [comment]
Works great! Thanks Marcel.
