### ISSUE TITLE
unable to move to search results if no movies returned 

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#38]
see picture - if your search does not return a movie you can't move to the results area

this issue is on rev .79 of helix skin

![2015-04-10_03-28-23](https://cloud.githubusercontent.com/assets/6510026/7086116/1a2d5606-df32-11e4-9486-160de1382a0b.png)

**Comment by marcelveldt** [comment]
fixed on git, will push new beta out.
Thanks for your attention!
