### ISSUE TITLE
request: display tag/label in footer area in views such as panel square

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#4]
should either by default or option toggle (in side menu) display the label/tag of the selected/highlighted item in the footer area in the add-on/media display of the following views:

panel square
panel square details
thumbs
thumbs details
poster row
shift
landscape
panel wall
big panel
fan art
single poster

**Comment by marcelveldt** [comment]
isn't it like this already ? That's how I coded it as I recall ;-)

It should display the title/label in the footer if no clearlogo exists for the selected item.

**Comment by mgonzales71** [comment]
Not in video add ons - in all those views the footer remains blank 

Try it yourself - if it works let me know :)

Thanks

**Comment by marcelveldt** [comment]
Now I see... when you set the clearlogo to show in the upper right the label is hideen.
Will change it :-)

**Comment by marcelveldt** [comment]
fixed!

**Comment by mgonzales71** [comment]
hmmm - do clear logos work in video add-ons?  well anyway - thanks for fixing :)  hehe
as always you are awesome Marcel!

mario
