### ISSUE TITLE
Question - Color Themes Mod (Concept, WIP)

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#45]
Marcel,

I was playing around with a concept:

option to use color themes (predefined and included with the skin)

I found this site - http://www.colourlovers.com/  has lots of great color pallets to choose from for just such a thing.

here is a modified skinsettings and a couple quick/rough color "themes" - not at all final quality - just  made a few for testing.

https://dl.dropboxusercontent.com/u/2203431/titan%20color%20themes%20mod.zip

try out the code and let me know what u think...

basically just adds a setting that

enables the color themes selection in Appearance Settings
or
allows custom color selections via Skin Settings (as it exists now)

the thinking is to use the site I shared above to come up with some pleasing "themes" to include for use if the users don't want to bother fussing with custom options but instead just want to cycle through some nice ones you include with the skin.

Can't quite get it all to work correctly - the settings go back to "defaults" every time you re-enter skin settings - I thought I had the onload statements set up correctly to only go to defaults if nothing was set or it was set wrong.

couple pics

![2015-04-20_14-31-49](https://cloud.githubusercontent.com/assets/6510026/7241120/7fadba7a-e76b-11e4-8c62-b1a2e3e69b8f.png)
![2015-04-20_14-32-16](https://cloud.githubusercontent.com/assets/6510026/7241122/8224bb6e-e76b-11e4-9324-9b4fca3a2f5a.png)

what am I doing wrong? - I am sure it's so obvious LOL

if you like the idea or any parts of it - feel free to fix/alter/trash any or all of it....

:-)

thanks sir!!

Mario

**Comment by mgonzales71** [comment]
Example 

http://www.colourlovers.com/palette/110225/Vintage_Modern

![2015-04-20_18-08-19](https://cloud.githubusercontent.com/assets/6510026/7243899/649a2864-e788-11e4-9873-9a93a2e032be.png)


![2015-04-20_18-01-11](https://cloud.githubusercontent.com/assets/6510026/7243827/a0bca836-e787-11e4-8d6c-185ec8cf7536.png)
![2015-04-20_18-01-39](https://cloud.githubusercontent.com/assets/6510026/7243826/a0ba2d9a-e787-11e4-9f37-92f11c7aceb8.jpg)

**Comment by marcelveldt** [comment]
Hey Mario, I was think about this...What about "skin presets" ?
So, we create some skin settings with colors, overlay, transparency etc. and let the user choose from a couple ?

**Comment by mgonzales71** [comment]
that sounds nice as well - I was actually playing around with learning about the colors selection in the appearance settings menu. and I almost had things working but got stuck on that one issue.  you dont have to make this change to the skin - but if you liked the idea I am for it :-)  

I like to play around to learn about skinning as you have seen from the past hehehe 
it gets to be addictive! :)

I like your idea too - so we can close this or leave it open for your new idea - either way.

I finally figured out my issue with the original problem - I needed to combine conditional statements together with a + to get the proper behaviour.

**Comment by marcelveldt** [comment]
I think the main goal should be to create something like the Aeon MXQ skin has.
Just a bunch of different colours to choose from for (almost) every element in the skin.

Offcourse all these color/appearance settings hould have really good moderate defaults because I don't want to scare of the less experienced users. The defaults should be really great.

Besides that "master default" we can create some more default settings.
Applying such a default would just set a whole bunch of those color/skin settings at once.

For example:

- Apply skin default appearance settings
- Apply Arctic appearance settings
- Apply dark appearance settings
etc.

Pressing such a button will execute a whole bunch of "SetBool and Skin.SetString" commands...

Can you follow up ?

My main preference would be to re-skin the whole skin settings sections to a more user friendly approach like Aeon MXQ did with presenting the colors to click on (select from) etc.

For the presets you can create some screenshots as buttons to click on and so on...

**Comment by mgonzales71** [comment]
I've never used the MXQ fork of Aeon - Will have to check it out to see what you are talking about.

I know I have seem something akin to the "light" and "dark" themes in skins Nebula and Artic Zephyr.

For me the whole idea of even playing around with this as a mod for skin was the limited color choices or "palette" in the skin.

Your light / dark suggestion - that is a good idea for novice users as you said to get a quick and easy theme change for the "modern" branch of Titan - but does not address the limited color selection.

I don't know the real solution to that issue - maybe added a settings toggle under Advanced in Skin Settings to let users enable "Advanced Color Selection" - that would allow the user to enter a color in the ARGB hex notation?  (ie FF002233) - too extreme? ;-)

**Comment by mgonzales71** [comment]
Oh - and as an FYI - Kodi / XBMC supports by _name_ all the colors listed in section 4.3. "Extended color keywords" at the following link http://www.w3.org/TR/css3-color/#colorunits - I saw the xml file and that link it in the Kodi Git repo code - I don't have the link handy but I've tested various names and they work as expected.

At the very least maybe we could even just expand the current color choices in the skin a little bit by choosing some colors from that list since they are "built-in" supported colors via the app?

**Comment by mgonzales71** [comment]
found it - https://github.com/xbmc/xbmc/blob/master/system/colors.xml

**Comment by mgonzales71** [comment]
What do you think about something like this to select colors?

![screenshot001](https://cloud.githubusercontent.com/assets/6510026/7543050/76fe3742-f576-11e4-9cc2-12db03e31e66.png)

built this off searchdialog.xml 

I kind of like it :)

**Comment by mgonzales71** [comment]
test dialog for HeaderTextColor with fully defined color list:

![2015-05-08_14-30-28](https://cloud.githubusercontent.com/assets/6510026/7546203/34566ed6-f590-11e4-8690-642bb26a2a7c.png)

**Comment by marcelveldt** [comment]
Hey Mario,

sorry for commenting on this so late, I don't always get the email notifications from Github...
This is exactly what I meant that should be done, it is great.

I'm not sure however if it's possible to show this dialog for all settings easily ?
If not  can create some python code for it so you just have to "feed" it the skin string that needs to be set and it will open the dialog...

So, what I'm thinking off is both this (a nice selector with many, many colors to choose from) to set each individual item yourself AND some nice "presets" to choose from..

This will be a great feature!

**Comment by mgonzales71** [comment]
i was thinking of asking if you could maybe add this to the helper script 
like a function:  passing to the helper something like:  XBMC.RunScript(script.titanskin.helpers,CHOOSECOLOR) or XBMC.RunScript(script.titanskin.helpers,CHOOSEBUTTONFOCUSCOLOR)?

and also

XBMC.RunScript(script.titanskin.helpers,SETLIGHTTHEME) / XBMC.RunScript(script.titanskin.helpers,SETDARKTHEME) ?

that would save on needing a bunch of files like this http://pastebin.com/ZCm1L03u

**Comment by marcelveldt** [comment]
I am going to rework the entire skin appearance settings like you suggested.
Will build a custom color picker in the image script to set any of the skinsettings with a chosen color from the dialog.

I think it's nice to get a whole bunch of colors in that dialog so that it would set everyone's need.

When that's finished I'll create some possibility to save and set presets for the skin. Fo example we can create a "artctic preset" which will make the skin feel like the popular artctic skin just by setting the correct appearance settings in titan skin.

Will keep you posted as soon as I have the first work done on this.

**Comment by mgonzales71** [comment]
yea -  I really like the idea of that too!  

maybe make the keys a little smaller yet and make the "keyboard" wider with colors taken from the built-in Kodi defined colors (http://www.w3.org/TR/css3-color/#colorunits) and the ability to load/save defined sets is an _excelent_ solution to themes indeed!

I've not really seen this in any other skins - so this will be very nice indeed,

closest is arctic: zephyr that recently has added selection for color but only focus color:

![2015-05-15_16-09-51](https://cloud.githubusercontent.com/assets/6510026/7663292/edb25f02-fb1c-11e4-8ef8-516a5e0bf464.png)

even you even wanted to go so bold as to allow the ability to enter colors as ARGB hex code (advanced button?) or load user defined xml file "sets" with custom ARGB entries? 

can a skin read/write data from/to say.. \userdata\addon_data\skin.helix\ ? or could just use the helper script's addon_data folder if not.  just seems like using guisettings could get messy maybe? 

I am excited by this new feature indeed!! :) hehe

**Comment by marcelveldt** [comment]
Hi Mario, good news!

I've made the first progress with the Color picker. If you check out the latest git version of both the skin and the helper script you can have a play with it...

All colors that can be chosen from are in the "colors.xml" file in the helper script's resources directory.
I Just copied over a file I found on the web so that file needs reviewing to add all sorts of colors to it.

The first appearance settings are adjusted to use the colorpicker, take a look how easy it is :-)

**Comment by mgonzales71** [comment]
ooooh i just saw this - going to grab it now :)

**Comment by mgonzales71** [comment]
Amazing work Marcel!  :)

couple of thoughts...

I haven't had a chance to test it out on a touch/mouse device yet - so may need to verify all is good there.

also - what about low power systems?  maybe a simple color picker for those if needed?

I will jump back into testing and comment more later - first impression.. very cool!!

**Comment by mgonzales71** [comment]
some more thoughts:

convert all the ARGB hex to lowercase (ie ff112233 except the ones you want at the top of the list) and then sort the colors in the color picker by ARGB alphabetically - it will make the color pallet more "uniform" for the color selection - try it and you will see what I mean.

In skin settings (this may be not needed if you add the ability to load and save color themes - but a "reset all colors to defaults" would be nice if that feature is not added - if it is a "defaults" theme will solve this)

I love the expanded skin color selection options too!

**Comment by mgonzales71** [comment]
oh i like that you have the color names - so if you do sort the list as I suggested - still leave the names.

I guess you could have a side slider option tab with sort by name or ARGB if you are torn on which to go with,

**Comment by marcelveldt** [comment]
Mario,

The colorthemes/presets are the next step, first I'd like to get this colorpicker thing ready.
Already pushed it to the skin beta to let some users test/comment it.

I just checked in a change on Github that will sort the list on argb value, please try if it is what you mean.

**Comment by mgonzales71** [comment]
can you sort by ARGB like you did but in the list be able to type like - B-L-A and jump to the name "Black" like it did when you sorted by the color's name before the sort change?

**Comment by marcelveldt** [comment]
I'm afraid that won't be possible.. the list is sorted on ARGB or the name... The only thing I can think of is to add a toggle to switch between them.

**Comment by mgonzales71** [comment]
hmm - well a toggle is better then nothing - plus both sorting methods are helpful anyway

**Comment by mgonzales71** [comment]
hey - I noticed every time the color picker comes up now, it starts on the same color (not the color currently set) - before it would remember (I think).

Also another thing I noticed.  if you hold down (shift) and type b-l-a-c-k real quick it will jump to black. 

same for other letters  (shift) g-r will jump to (gr)een or variants of.

maybe there should be at the top of the list a grouping (using capital letters in ARGB for sorting or by code) of "a basic color list" roy-g-biv (red-orange-yellow-green-blue-indigo-violet), black, white, grey, etc (the colors you would for instance see in a basic "paint" program) 

could display just these basic colors on "low powered" systems if for instance the Pi is having problems with this feature - I don't have access to one to try it out - do you?

that's all for now on thoughts for this feature - love what you have done so far!!!!!

thanks again sir!

**Comment by marcelveldt** [comment]
Hi Mario, will look at your issues/suggestions later. As for the performance: It should work well on low poewred devices too altough I didn''t test it yet.

I've done the first work today on another very cool feature.. The skin themes support.
Please check out the latest git version and give it a try. Cool is that you can save your settings in the skin to a preset. The preset is saved to a file so users will be able to setup the skin to their liking and share the preset with the reset of the world. Please feel free to make some presets and send them to me.

I will let you know how to include extra "skin defined presets" into the skin later

**Comment by mgonzales71** [comment]
ok - let me go sync up git and install and test for you.

off topic - I noticed a real quick "check mark - box" thing earlier and i thought I was seeing things - found you had added that to dialogselect - i didn't know you could do that hehe 

that could be useful for touch screen folks who have like a slower tablet to know that input was received and they just need to be patient.

**Comment by marcelveldt** [comment]
yeah, the default was a radiobutton in there which I didn't really like so I added a checkbox to both the dialogselect and the filemanager.

**Comment by mgonzales71** [comment]
was it included for the reason I speculated?

haven't fired up the skin update just yet - so i could answer this myself by doing so 
but... how far do themes go?

are for example - backgrounds, custom overlays, etc saved?

let me just go and test this - all excited to see 

brb :smile:

**Comment by marcelveldt** [comment]
all appearance settings should be covered, so all color settings.

No custom backgrounds or overlays because that will mean I have to copy the file sover or something..

**Comment by mgonzales71** [comment]
here is a theme for you to test - https://onedrive.live.com/redir.aspx?cid=599da6bd82779e65&resid=599DA6BD82779E65!4606&parId=599DA6BD82779E65!4605&authkey=!AJihvTYvK-n_Yws&ithint=file%2czip

when I created a theme - after saving it my color settings changed to I am guessing "default" but I was able to select what I just saved and restore them.

**Comment by marcelveldt** [comment]
yeah, there are a few bugs in there which I need to fix.. I will give your theme a go

**Comment by mgonzales71** [comment]
since you offer a screenshot with the theme - maybe you want to zip them together?  don't know if that is available across platforms or not - so could be problematic - if they can share a ,theme file I am guessing they can handle a jpeg too hehe

**Comment by mgonzales71** [comment]
i noticed you save titanskin.* and titanskin.helix.* - may want to check what skin is in use and exclude other settings - could end up with a theme changing settings in wrong skin

**Comment by mgonzales71** [comment]
be aware of that in case you don't want settings changed in the other skin if you load theme I sent

**Comment by mgonzales71** [comment]
if you get odd settings like -["bool", "TITANSKIN.EnableSkinColorTheme", "false"], ["bool", "TITANSKIN.EnableSkinColorExpertMode", "false"], ["bool", "TITANSKIN.ExpertColorMode", "false"] it was from me testing theme and colors like this at early stages on my own :smirk:

**Comment by marcelveldt** [comment]
1) yeah, I can zip it too but I need fast access to the files for the listings so decided to leave the two files apart... It's working btw: just installed your green theme :-)

2) Please pull latest changes from the zkin and test, fixed a few things.

3) Look in the skin "extras" subfolder. I've added your Envy theme there too. So in that folder we can provide themes to include with the skin. Open the theme file in notepad++ and notice the first settings: you can type an alternate listing name in there and a discription. The other stuff should be left alone.

4) Yeah you're right about skin.titan and skin.titan.helix but nothing that can be done about it because of the way that stuff is stored. skin.titan.helix and skin.titan both contain the phrase skin.titan...

**Comment by marcelveldt** [comment]
5) Please test if all settings are indeed stored in the theme. I store every skin setting that contains "Color" or "Opacity", I might want to add some more if I know which. 

Please test and let me know if anything should be added to make it a valid feature.

Also, if you like, add some themes to the skin folder in a PR.

**Comment by marcelveldt** [comment]
6) Oh and don't know if you noticed but I have also enabled a contextmenu for the theme entries, do delete your custom themes etc.

**Comment by mgonzales71** [comment]
re: "4) Yeah you're right about skin.titan and skin.titan.helix but nothing that can be done about it because of the way that stuff is stored. skin.titan.helix and skin.titan both contain the phrase skin.titan..." 

if running helix - grab only titanskin.helix.*  (grep "titanskin.helix." > .theme)

if running isengard - grab only titanskin.isengard.* 
(grep blah blah... hehe)

and add as new skin variants are released 

if running just titanskin do something like grep -v "titanskin.helix." | grep -v "titanskin.isengard." > .theme?

i saw the context menu - may want to add "change thumbnail" to the list

let me go grab an update and do more testing :)

**Comment by marcelveldt** [comment]
The official version of the skin is always named skin.titan... so for Gotham, Helix and Isengard it's always just skin.titan.

Only the beta has been prefixed with .helix back then...

I get every setting in Kodi that begins with the skinname. When you have both the beta installed and the stable iut will grab skin.titan.helix too if you do this from the stable version. If you run from the beta there's no issue.

**Comment by mgonzales71** [comment]
ah ok - when i better go clean up the .theme you checked in because I saw it has some settings I had used for personal testing - oops :) hehe

after I installed the latest from Git the color theme panel was blank - I did a reload skin and re-installed the helper and it shows now - dont know which of those two fixed it what was going on

I didn't see any errors in the log file... 

I guess if it doesn't happen again it can be ignored - just was weird

I will play around more today and get some theme's together and let you know if I have any suggestions.

** one thought I just had is - maybe create a window/dialog that can be loaded for screenshots (custom_colortheme-preview.xml?)  that shows off the various colors all on one screen -- could add it under the context menu as "preview" - that way all the screenshots would look similar and also allow folks to "preview" a theme in a standard way as well.

this would pair nicely with a context menu option to "add / change thumbnail" **

**Comment by marcelveldt** [comment]
OK, please test and report any issues or requests you may find.

As for the preview.. Isn't that where the thumb is for ?
I can add in a preview which will show the screenshot fullscreen ?

**Comment by mgonzales71** [comment]
no preview would load a custom_ .xml file 

if would be a test page that shows the various color theme settings on one windows/dialog/screen.

could show a fake header, fake footer, a panel with opacity, the overlay with opacity, focused button, unfocused button, list, media list, sample home tile image, etc all on one test page.

that would also let folks use that to grab a screenshot that was common/same that showed all color settings at once  - letting them share the image online but also save as a thumbnail 

that added benefit of a preview feature that would load that page with the settings of the theme to let users preview in skin and then go back to the settings they had before after viewing it
(onload to save current to temp fie, onunload to restore?)

so you would need to I guess save settings in a temp file, load the settings from the theme, display the preview page, then re-load the saved settings from the temp file to go back to what was set.

I know i am doing a bad job of explaining this - sorry.

don't worry - let me focus on testing and making some theme to share and I will let you know if I find any issues / more suggestions.

**Comment by marcelveldt** [comment]
well, that would be a whole different story and a lot of work. Don't even know if it's possible.
Let's first work with this and the screenshots and maybe add extend with that feature later on.

I was just thinking... would it be a good addition to let the user choose from some overlay images ? That way you can choose a overlay image/texture, choose the color for the overlay and you can even choose a custom overlay.

**Comment by mgonzales71** [comment]
I think so - the overlays I created had a diffused texture component in addition to the color component.
so you could want one or the other or both.
so - allow color overlay choices (with none as an option) and also maybe restore the orig overlays and the ability to have none or a custom one.

what I was talking about above was something like this:

http://pastebin.com/bCiGbfn4

copy that to a file named "Custom_ColorThemePreview.xml" in your 1080i folder, reload the skin and then create a shortcut or keybinding to do this command: ActivateWindow(1122)

this is what I quickly threw together to show you sort of what I meant...

![2015-05-22_14-15-05](https://cloud.githubusercontent.com/assets/6510026/7779841/04b8329c-008d-11e5-8020-441db768f83e.png)

it still doesn't show and example of the media text colors but you get the direction I was going...
you could load a theme temporarily - display this window and then onunload restore the settings to what they were before previewing.

**Comment by mgonzales71** [comment]
Latest:  

http://pastebin.com/WfsBKgyd

I need to work on some color themes now so I will stop playing around with this preview page
if you want to expand on it, use it, etc you are welcome to,  to-do: OSD panel opacity, media details panel opacity, general panel color and opacity - was going to make 3 equal sized panels on the right as examples and maybe text label in the panel with it's %'s - think that is all that needs to be shown in a preview unless I forgot something.

![2015-05-22_16-15-30](https://cloud.githubusercontent.com/assets/6510026/7781141/d0e83078-009d-11e5-9d99-416c469e8529.png)

**Comment by mgonzales71** [comment]
here is what modern default preview looks like:

![Uploading 2015-05-22_16-17-34.png…]()

**Comment by mgonzales71** [comment]
I think you should allow the user to set colors _and_ opacity for:

footer panel
media details panel
osd panel
other / general panels (create)
.
here is the latest work done on preview dialog/window...

moved it to the resources folder of the helper script.

![2015-05-23_05-37-11](https://cloud.githubusercontent.com/assets/6510026/7784124/3f250784-010f-11e5-8008-80631a2253e6.png)

**Comment by marcelveldt** [comment]
OK, I will add the extra options in. So for the panels we will have:

- footer panel color and opacity
- general panels color and opacity
- media details panels color and opacity

right ?

I will also change the overlay section a bit so the user can change the overlay texture from the bgoverlays folder

Please pull latest version as I changed a lot of all the textures in the skin. mostly to get a consquent experience across the skin and minimize differences between classic and normal theme

**Comment by mgonzales71** [comment]
dont forget OSD pean color and opacity too.

**Comment by marcelveldt** [comment]
OK, I'm currently adding the overlay texture selection dialog.. Will checkin in in a few minutes. Will add the extra panel color settings after that.

**Comment by mgonzales71** [comment]
ok - re-grabbed laetst copy about to look at it and test now.

I re-did the PR btw - i messed up my repo trying to do that squash thing.

I spent an hour trying to fix it - ended up deleting and reforking the repo,, sigh.

**Comment by marcelveldt** [comment]
Hmmm, I was just thinking.. I can offcouyrse do the merge but you might want to change the color themes again after I'm finished with all the new color settings you asked..

What do you think ?

**Comment by marcelveldt** [comment]
I can oofcourse merge and that you alter the themes later on ?

**Comment by mgonzales71** [comment]
go ahead and merge what I have i will update them later.

I looked at the overlay image + overlay color - it seems like color does not affect the image unless you set opacity to 100 - try a test and see what you get.

like pick a light color texture and then try to add a color like red or bright yellow or dark blue

**Comment by marcelveldt** [comment]
We need to replace the overlay images with other ones that actually contain white levels because only white will be replaced by the color setting.. So it's not an issue in the skin, it's a problem with the overlay textures. You can give it a good test if you pick the winter overlays which actually contain white levels

**Comment by mgonzales71** [comment]
ok - it works slightly at 100% but makes sense 

Here is a quick one for you to try and add to skin if you like

http://i.imgur.com/sTzPIbu.png

I named it "High & Low Diffuse Overlay.png"

**Comment by marcelveldt** [comment]
OK, I've added the additional opacity and color settings. Just checked in to git.
I've also placed your high&low diffuse in the available overlays.

If you want to add any additional overlays: just place them in the bgoverlays folder and it will work.

**Comment by mgonzales71** [comment]
ok - will come up with some more - I sort of like that high/low one - was just one I  made real quick - funny how that happens

**Comment by mgonzales71** [comment]
I love the new panel color and opacity options 

you have a typo in the skin settings 
footer panel color: color
footer panel color: 80  (should say opacity):

that is the only issue I have seen so far with all the changes.

wow!  impressive Marcel!

OH - and that preview window I was throwing together - it needs alot of changes already.

But now that I threw something together - does it make sense what I was trying to say before?

I know I was doing a horrible job of explaining it - hopefully that made it clearer (maybe? LOL) :smirk_cat:

**Comment by marcelveldt** [comment]
OK, fixed that last one too.... I will be out tonight. Will work on the new OSD icons tomorrow. Maybe I need to add some color settings for the OSD too, will see how it goes.

Oh, the color themes need to be adjusted for the new color settings, even the default ones. Will look at the default ones tomorrow.

Your preview panel will be included some later because I need to adjust it to work with the helper script. I want to create something so that the preview doesn't need to have the skin settings actually present. Will work on that later this week.

Thanks for your help!

**Comment by mgonzales71** [comment]
Enjoy your night and have fun - it's a holiday weekend here in the US so we have a couple of family cook-out/bbq's nothing major - I will work on themes, testing, etc

I sent you a message via the forum - the OSD buttons are fuzzy / different sizes so not sure if you will pull the trigger on them yet or not..

hopefully simograndi can re-work them to be sharper, more consistent 

hopefully the links I shared with him may be of help/inspiration

**Comment by mgonzales71** [comment]
sorry - got caught up in family stuff yesterday (and have more coming over today) but I wanted to get in some testing of updates to the skin for you.

I like the revised OSD buttons :)

slight cosmetic issue with slim OSD panel (see below)

![2015-05-25_08-22-43](https://cloud.githubusercontent.com/assets/6510026/7799164/a208f5b4-02b7-11e5-8ccf-e37c19af3d51.jpg)

also - with the slim panel should the weather on OSD be an option still or no?

If so I can adjust it to fit better or we can leave it out - I personally will be using the full size OSD so it doesn't impact me anyway.

**Comment by marcelveldt** [comment]
the slim panel needs some more work.. will fix asap. These icons are not the final ones, just some I put in waiting for the final ones to come from simograndi.

I disabled the weather for the slim panel. It's more something for the full blown OSD.

Once simograndi finishes the icons I will put them in and after some testing I'll release another beta. Lot's of stuff changed for people to test :-)

**Comment by mgonzales71** [comment]
one other slight cosmetic issue - missing pause symbol (evething shifts for it's display but it is missing)
![2015-05-25_08-32-43](https://cloud.githubusercontent.com/assets/6510026/7799267/d1f60a90-02b8-11e5-8ad0-a3ebb15efaac.jpg)

**Comment by marcelveldt** [comment]
BTW: quick question: Do you think I need to add a textcolor option for the osd panel ?
Now I've used the media details colors for the osd too. Also for the progress bar I've used the button focus color...

**Comment by mgonzales71** [comment]
well I like the new OSD icons you have in as temps :smile: - hope his new ones are just as good or better!  - everything is looking really good!  I think I am going to hold off on updating themes until the dust settles.

you can remove them temporarily if you like until then 

OSD text color would be good (and shadow)
while you are at it add shadow for footer as well now that you can color it.
I suppose anywhere you can pick a text color you should be able to also have a shadow option.

**Comment by mgonzales71** [comment]
this is looking to be a HUGE update - very impressive - loving it all!!
great work Marcel!  as always you are the man! :+1:

**Comment by marcelveldt** [comment]
OK, I'll add the extra color options.

**Comment by marcelveldt** [comment]
haha, yeah It's a major update and indeed looking good. Thanks for all your help !!!

**Comment by mgonzales71** [comment]
you are most welcome!  - any yea - options - seem to please the masses best :smile:

**Comment by mgonzales71** [comment]
may want to make the "nib" of the slider slightly transparent - it was a request a long while back from the forum to do so.

![2015-05-25_08-43-16](https://cloud.githubusercontent.com/assets/6510026/7799379/3916687c-02ba-11e5-8301-df1aa37c9f68.jpg)

**Comment by marcelveldt** [comment]
the slider background texture already is slightly transparent.

**Comment by mgonzales71** [comment]
the nib is as well?  the little square you grab and slide back and forth?

**Comment by marcelveldt** [comment]
no, that one is filled 100% otherwise it would be very hard to notice it...

**Comment by mgonzales71** [comment]
noticed slight clipping of text in OSD in certain instances

![2015-05-25_13-48-01](https://cloud.githubusercontent.com/assets/6510026/7802157/0dd4c156-02e5-11e5-999b-2fb7b1529b04.png)
![2015-05-25_13-48-13](https://cloud.githubusercontent.com/assets/6510026/7802158/0dd7e5de-02e5-11e5-980e-83de761e80f1.png)

**Comment by mgonzales71** [comment]
FYI - looks like a texture was moved for the bg panel of Custom Search....

![screenshot000](https://cloud.githubusercontent.com/assets/6510026/7816446/4be76d4c-0383-11e5-88a3-88371650255c.png)

**Comment by marcelveldt** [comment]
That will occur if you resize the window... Nothing IU can do about that. Label size is 940 pixels so plenty of space there

**Comment by marcelveldt** [comment]
Ah, thanks for the catch. Fixed the search window

**Comment by marcelveldt** [comment]
OK, I'm about to push another beta out. Will leave your color themes out for now because they're not compatible with the current modifications to the colors. You can submit a PR to put them back in if you want.

For the OSD icons: I will leave it as-is for now as I'm not convinced about the circles and the way it looks like when colored. We can work on this later on.

Same for the radiobuttons.. The only think I can think of to improve them is by using a whole other texture, for example the windows 8 style toggles...

**Comment by mgonzales71** [comment]
I just posted a PR with 3 updated themes

**Comment by mgonzales71** [comment]
I like the new OSD buttons btw

**Comment by mgonzales71** [comment]
tiny alignment issue with OSD buffer indicator in progress bar
 
![2015-05-29_09-50-21](https://cloud.githubusercontent.com/assets/6510026/7887785/86598a02-05e8-11e5-9a97-a6964d9bf0d3.jpg)

**Comment by mgonzales71** [comment]
it just dawned on me - that may be by design... if so maybe you could add a couple more pixels?

**Comment by mgonzales71** [comment]
maybe something like..?

not sold on either one as is but maybe you have an idea of something?

![a](https://cloud.githubusercontent.com/assets/6510026/7888397/485f4b56-05ed-11e5-9778-3e7ebcdc20e9.png)
![b](https://cloud.githubusercontent.com/assets/6510026/7888398/48600960-05ed-11e5-8816-02e2214b8cfe.jpg)

**Comment by marcelveldt** [comment]
I removed the cache progress bar for now as it was causing me a headache... For some stupid reason it doesn't want to be positioned... Seems like a bug in Kodi or something.
Will look into it later, wonder if anyone even notices that cache progress bar anyway...

**Comment by marcelveldt** [comment]
I'm going to close this issue because the Original issue has been resolved; the skin now supports color themes. Please create a new one for different issues because this one is getting a bit hard to read ;-)
