### ISSUE TITLE
Bug: Met Office Weather - Feels Like / Missing Logo 

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#51]
In testing the Current Weather On Home Skin Setting option I noticed the following with "Met Office" weather provider:

"feels like" weather temp was obviously not right and the weather provider logo wasn't being displayed (missing).

now - the "feels like" could be that I use F instead of C maybe?

But not sure about the missing Logo.

Maybe you could you test on your system?

![2015-04-26_14-36-41](https://cloud.githubusercontent.com/assets/6510026/7339411/68801756-ec22-11e4-9c44-eef8cbace823.jpg)

**Comment by marcelveldt** [comment]
Met Office is wrong on my system too...

Logo is missing and "feels like" temperature is wrong.

**Comment by mgonzales71** [comment]
I am guessing this is an add-on issue.

Opened an "issue" ticket with the provider's repo

https://github.com/powlo/weather.metoffice/issues/3

probably ok to close this ticket and hope they address the issue in the next update.

**Comment by marcelveldt** [comment]
OK, thanks!
