### ISSUE TITLE
BUG - Show Video Infomation on Pause -- Broken

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#54]
Seems changes were made to the skins behavior in regards to the skin setting: "Show Video Information on Pause"

When set and playback is Paused it does not honor the following setting:

![screenshot001](https://cloud.githubusercontent.com/assets/6510026/7356347/4cc9a9a4-ecdc-11e4-9245-548dc22faad7.png)

Only PAUSED is displayed - no video info.

![screenshot000](https://cloud.githubusercontent.com/assets/6510026/7356535/aa9ae9e8-ecdd-11e4-83c3-14a6a9151861.png)

Can we please go back to the expected behavior? 

I know I read one guy complaining about this in the forum - he did not seem to understand what Plot and Video Info are -- and the skin settings to enable/disable the display of such elements.

![2015-04-27_12-57-33](https://cloud.githubusercontent.com/assets/6510026/7356503/69a7f48a-ecdd-11e4-990a-c382550f208c.png)

So when this setting is enabled only the bottom part should be displayed on Pause - the Info (not the Plot),

With the latest changes I have to press "I" when Paused to get video info (and that displays the plot too)

Hopefully we can go back to how it worked before.

Appears the changes were made in this commit:

https://github.com/marcelveldt/xbmc.skin.titan/commit/16145fbdd3ac88295247cec0f737d57e63bfe631

The code hi-lighted in yellow is the original code the worked as expected - I tested reverting to that code again and it seemed to have restored things.

![2015-04-27_13-36-39](https://cloud.githubusercontent.com/assets/6510026/7357379/34b54aa6-ece3-11e4-866e-cfbcdf3322da.png)

Thanks Marcel!!

Mario

**Comment by marcelveldt** [comment]
thanks Mario, this was indeed a bug... Fixed it in the code, will provide new beta tomorrow when I fixed some more stuff asked on the forums.
