### ISSUE TITLE
font12 definition, window header text & text entry focus

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#57]
See: https://github.com/tknorris/salts/issues/86

seems Titan has some issues when it encounters an add-on that includes skin resources that are using confluence as a baseline.

one being a missing font12 definition, and apparently window header and text entry focus (both not displaying).

I can do a pull request after adding the font definition for font12 - actually should look and make sure all the default confluence fonts are defined for the skin just in case,

Do you have any insight into the window header text and text entry focus?

one of the includes maybe?   I need to read up on those skin elements - still a novice at skin dev. :)

Thanks goes out to tknorris for the assistance

**What it should look like:**

![screenshot001](https://cloud.githubusercontent.com/assets/6510026/7449153/2cca6f5a-f1e4-11e4-995d-6d7ce59e303e.png)

**What it does look like:**

![screenshot003](https://cloud.githubusercontent.com/assets/6510026/7449154/2ccbe9fc-f1e4-11e4-9bc5-b884d28b4746.png)

**Comment by mgonzales71** [comment]
Marcel,

It looks like confluence defines these baseline font names in all of it's fontsets:

	<fontset id="Default" idloc="31390"> 
		
		<font>
			<name>font10</name>
			<filename>Roboto-Regular.ttf</filename>
			<size>14</size>
		</font>
		<font>
			<name>font12</name>
			<filename>Roboto-Regular.ttf</filename>
			<size>17</size>
		</font>
		<font>
			<name>font13</name>
			<filename>Roboto-Regular.ttf</filename>
			<size>20</size>
		</font>
		<font>
			<name>font14</name>
			<filename>Roboto-Regular.ttf</filename>
			<size>22</size>
		</font>
		<font>
			<name>font16</name>
			<filename>Roboto-Regular.ttf</filename>
			<size>25</size>
		</font>
		<font>
			<name>font30</name>
			<filename>Roboto-Regular.ttf</filename>
			<size>30</size>
		</font>
		<font>
			<name>fontContextMenu</name>
			<filename>Roboto-Regular.ttf</filename>
			<size>18</size>
		</font>


		
		<font>
			<name>font10_title</name>
			<filename>Roboto-Bold.ttf</filename>
			<size>12</size>
		</font>
		<font>
			<name>font12_title</name>
			<filename>Roboto-Bold.ttf</filename>
			<size>17</size>
		</font>
		<font>
			<name>font13_title</name>
			<filename>Roboto-Bold.ttf</filename>
			<size>20</size>
		</font>
		<font>
			<name>font24_title</name>
			<filename>Roboto-Bold.ttf</filename>
			<size>24</size>
		</font>
		<font>
			<name>font28_title</name>
			<filename>Roboto-Bold.ttf</filename>
			<size>28</size>
		</font>
		<font>
			<name>font30_title</name>
			<filename>Roboto-Bold.ttf</filename>
			<size>30</size>
		</font>
		<font>
			<name>font35_title</name>
			<filename>Roboto-Bold.ttf</filename>
			<size>35</size>
		</font>

		<font>
			<name>font_MainMenu</name>
			<filename>Roboto-Bold.ttf</filename>
			<size>40</size>
		</font>
		<font>
			<name>WeatherTemp</name>
			<filename>Roboto-Bold.ttf</filename>
			<size>80</size>
		</font>
	</fontset>

Some are defined others are missing - since some of these use fonts and font sizes that differ (even from the Arial fontset defined in the skin confluence) - these changes will be a/of material impact to the skin and I don't want to make arbitrary choices for the font sizes that you want to correspond the the font names,  So I will leave it up to you to make those.  But I think it would be a good idea to include all the font names above in each the skins fontsets to be better compatible with add-ons that use (and rightly so) confluence and the skin resources they include.

**Comment by mgonzales71** [comment]
The missing Window / Dialog Header Text - never noticed that before.   But then it's not often I am in Confluence or another skin - but it's very noticeable in a side by side screenshot.

**Comment by tknorris** [comment]
I figured out the problem w/ the missing header text.

I'm using the "selected" color for text in the header and that color name is only defined for confluence. I can fix it by picking one of the universal color names. 

On a side note though, all the confluence dialogs use "selected" as the color of the dialog header text, so it might make sense including that color in the skin, but I don't mind switching to another color.

**Comment by mgonzales71** [comment]
that is easy to do and probably best for compatibility anyway.  way to go and thanks again!  

Just curious... is this the first time you have used the skin Titan?

Marcel openly welcome thoughts, suggestions, etc if you have any.   He is a great guy and has put together what has become my favorite skin,

**Comment by tknorris** [comment]
Yes, I always run Confluence because whatever I run has to be wife-friendly and I always know that Confluence will run on each Kodi upgrade. It would be mass chaos in my house if I upgraded Kodi and our normal skin didn't work for some period of time.

Also, when doing addon development, I always want things to work there first since that's the default skin.

**Comment by mgonzales71** [comment]
Marcel,

The only missing name defined colors from confluence that are not also a system named color are the following:

<colors>
	<color name="grey2">FF999999</color>
	<color name="grey3">FF505050</color>
	<color name="selected">FFEB9E17</color> (a gold/orange tone color http://www.colorhexa.com/eb9e17)
	<color name="invalid">FFFF0000</color>   (red)
</colors>

I suggest that they be added to the skin for compatibility - but maybe change that orange/gold ARGB hex to be the same as mainblue or white?

**Comment by mgonzales71** [comment]
Marcel,

Here are the Confluence Fonts (sizes) adjusted from 720 to 1080

http://pastebin.com/qnXxXktg

FYI - This conversion was generated by the Kodi skinning tool

**Comment by marcelveldt** [comment]
Hi Mario, could you do a PR for the font changes so I can merge it in with git ?

**Comment by mgonzales71** [comment]
Ok - I will go ahead and make my best guess for you -  but since you are not using Roboto for the default font set in your skin the font sizes (scale / progression of size) may have to be slightly altered.  Arial font set will be easy at least.

I will also make changes to the color defaults as well - you have a preference for the selected color?

I am thinking 
ff6495ed cornflowerblue 
http://www.color-hex.com/color/6495ed
![6495ed](https://cloud.githubusercontent.com/assets/6510026/7487437/7ba624fa-f36c-11e4-8de0-02081165f942.png)

invalid color I will keep red.

**Comment by mgonzales71** [comment]
Created PR:
https://github.com/marcelveldt/xbmc.skin.titan/pull/61

Here is how the dialog looks now (with these changes):

![screenshot000](https://cloud.githubusercontent.com/assets/6510026/7489339/838e1e70-f38a-11e4-8e3b-abe82fbb3c99.png)

Much better!

**---------
 Marcel - Still need to figure out why the buttons are so mangled and why the text entry focus color is not displaying
---------**

**Comment by tknorris** [comment]
The missing colors on the text box might be because add it in code rather than the xml. The strange thing is everythign else picks up the assets from the media folder of the addon but it doesn't seem to for the control I add from code. I might be able to fix it by copying the textures into the addon and then explicitly referring to them with a full path.

**Comment by mgonzales71** [comment]
Well I know the skin can have text entry focus color without an actual image/texture but I could not right off see where the code was to do that (my guess its being inherited but could not find where from):

this is screen shot of the skin's SearchDialog.xml:

![screenshot001](https://cloud.githubusercontent.com/assets/6510026/7489661/1edf3c76-f38e-11e4-9826-d0c7c0ba9209.png)

**Comment by tknorris** [comment]
The work around of copying the text entry textures into the addon and then referring to them explictly works fine, so I'll just do that in the next build. The only remaining issue is the buttons are a little funky. They're at least readable though.

**Comment by mgonzales71** [comment]
tknorris - 

I noticed in the Defaults.xml of the skin the textoffsetx was set to 50 (a pretty big number in my opinion but could change from skin to skin)

So decided to peek at your addon's TraktPinAuthDialog.xml file... specifically the button control group and I noticed you did not specify a textoffsetx which led to that large textoffsetx to be inherited from the skin.

So I made a few changes as a test....

note the changes to posx & width and the addition of textoffsetx

	<control type="group" id="9001">
			<control type="button" id="200">
				<description>Authorize Button</description>
				<posx>30</posx>
				<posy>460</posy>
				<width>130</width>
				<height>40</height>
				<align>center</align>
				<aligny>center</aligny>
				<label>Authorize</label>
				<font>font12_title</font>
				<textoffsetx>10</textoffsetx>
				<ondown>201</ondown>
				<onright>201</onright>
			</control>
			<control type="button" id="201">
				<description>Later Button</description>
				<posx>170</posx>
				<posy>460</posy>
				<width>170</width>
				<height>40</height>
				<align>center</align>
				<aligny>center</aligny>
				<label>Remind Me Later</label>
				<font>font12_title</font>
				<textoffsetx>10</textoffsetx>
				<onup>200</onup>
				<onleft>200</onleft>
				<ondown>202</ondown>
				<onright>202</onright>
			</control>
			<control type="button" id="202">
				<description>Never Button</description>
				<posx>350</posx>
				<posy>460</posy>
				<width>130</width>
				<height>40</height>
				<align>center</align>
				<aligny>center</aligny>
				<label>No Thanks</label>
				<font>font12_title</font>
				<textoffsetx>10</textoffsetx>
				<onup>201</onup>
				<onleft>201</onleft>
			</control>
		</control>

Result of these changes:

![screenshot000](https://cloud.githubusercontent.com/assets/6510026/7501819/de34c458-f3eb-11e4-8051-9158d8e6c46f.png)

Not saying you need to make these changes but i think the more explicit you are with control tags the better.  Also - the middle button had the most characters so I made it slightly wider adjusting the outer two to be less so by the amount donated to the middle button for balance <grin>

not that many skins would have a default for it - you could also explicitly state textoffsety as well.

**Comment by tknorris** [comment]
I'll definitely make those changes. That explains why so little of the text was showing up in this skin. Explicitly specifying the textoffset should fix that for everyone.

**Comment by tknorris** [comment]
I will push a new beta of SALTS tonight w/ the PIN auth dialog changes. That should get everyone running alternate skins to a point where the dialog can used even in the worst case scenarios.

**Comment by mgonzales71** [comment]
excellent!  thanks again for hanging in there and the assistance on this issue.  much appreciated for the and most importantly your awesome addon :)

**Comment by mgonzales71** [comment]
well now the only fear is that some skin will set font12_title to some insane size - LOL

**Comment by tknorris** [comment]
In the latest xml for the dialog I swapped the two paragraphs for that very reason. That way even if the text goes outside of the bounding box at the very least the first sentence will show up w/ the url in it.

**Comment by mgonzales71** [comment]
Grabbed a copy of your addon from Git repo and tested it out in the skin with the changes I made in the PR above...

Looks good!

![screenshot001](https://cloud.githubusercontent.com/assets/6510026/7502885/1c302916-f3f4-11e4-927c-d199c78c2dc6.png)

Marcel - if you are OK with the PR above you can close this issue. (thanks)

TK(norris) - Thanks again for the help!

**Comment by marcelveldt** [comment]
Thanks! Merged the changes in the skin.
