### ISSUE TITLE
FR: list with all views instead of toggle

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/xbmc.skin.titan#65]
Switch between the View modes options without pressing several times in order to go back to the previous mode in the modes list. Just press on the Views Modes and a list will open to choose from, or other solution which could make it easier. 

http://forum.kodi.tv/showthread.php?tid=227221&pid=2006615#pid2006615

**Comment by marcelveldt** [comment]
added to the skin helper to show a dialog with all views available

**Comment by mgonzales71** [comment]
I like!  great suggestion from the forum! :+1:

**Comment by marcelveldt** [comment]
needs to be applied to other sections too (music, pictures, programs, livetv)

**Comment by marcelveldt** [comment]
applied to all other sections and added forced views feature
