### ISSUE TITLE
FR: add option to choose between different watched overlay styles

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/xbmc.skin.titan#67]
http://forum.kodi.tv/showthread.php?tid=205482&pid=2009132#pid2009132

**Comment by marcelveldt** [comment]
- show sicsets item count or just disc icon ?
- difference between watched overlays/unwatched etc.

**Comment by mgonzales71** [comment]
movie sets could be like 3 overlapping DVD's with a number over top for the set for unwatched - all watched a check mark?

I kind of like these as an option maybe?
http://i57.tinypic.com/ua8ty.png   star-new/unwatched, check mark-watched, circle-partial

then you could offer similar to what you have:
blue triangle - with check mark for watched,  ##% for partial, and star for unwatched and # for number of new episodes, etc

**Comment by mgonzales71** [comment]
also http://i.imgur.com/uyJn1bm.jpg

**Comment by marcelveldt** [comment]
I will create options so you can choose from different icon styles.

**Comment by mgonzales71** [comment]
man marcel you are on fire this weekend :+1:

**Comment by marcelveldt** [comment]
haha, yes I wanted to fix some long standing feature requests...

**Comment by mgonzales71** [comment]
FR to consider when working on overlays for watched, etc..
Add them to the Info screen of Movies, TV Shows (and Seasons and Episodes)

example of episode
![2015-05-29_16-40-55](https://cloud.githubusercontent.com/assets/6510026/7894624/02757a36-0622-11e5-9b05-ea3608ff209a.jpg)

**Comment by marcelveldt** [comment]
great suggestion about adding the watched overlay to the videoinfo dialog. Just added it in.
