### ISSUE TITLE
FR: add trakt to side menu/blade for tv show episodes

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#69]
add trakt menu as it is for movies and tv shows to episodes as well.

![2015-05-22_00-35-52](https://cloud.githubusercontent.com/assets/6510026/7766135/0d96fb5e-001b-11e5-9fd1-50f3cfd38aed.jpg)

thanks! :)

**Comment by marcelveldt** [comment]
..done... please note that this will be changed as of Isengard because Isengard has a feature that lets addons add their own command to the sideblade menus.
