### ISSUE TITLE
BUG: Info (I) during playback does not display full Info (Ignores Plot display toggle in settings)

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#75]
BUG: Info (I) during playback does not display full Info (Ignores Plot display toggle in settings)

I have tried with setting in either position on and off and can't get it to display the top part of the OSD Info (plot) -- only the bottom OSD panel.  

I have tried it during playback and also when paused bringing up the media controls and trying the new (I) info button or (I) itself on the keyboard.

may want to test on your end and see if it works for you or not.

thanks

**Comment by marcelveldt** [comment]
works fine for me... Sure that the content you were testing with actually had a plot ?

**Comment by mgonzales71** [comment]
ok - i just restarted kodi and now it is working!?!?! - I swear.. I could not get the plot to display when I brought up full info display.  - weird.  I will keep an eye out on this.

sort of related to this - I could have swore that the show plot option in settings under OSD was getting unset too.. but again.. I can't for sure say that is the case.. yet :smile:

close this for now - if it happens again I will get more info for you.

**Comment by mgonzales71** [comment]
Ok - now I can't figure out how or why it is happening but this option keeps getting set to off.

Turn it on in your settings and after a couple hours (and maybe some testing of appearance settings, etc) making sure to not turn it off - check and see if it is still on.

somewhere there must be a rest or something happening?

I swear I am not going crazy! :open_mouth:

**Comment by mgonzales71** [comment]
Think I figured it out...

this bit of code in IncludesThemes.xml:

				<control type="button" id="808">
					
					<width>90</width>
                    <height>90</height>
					<label>31133</label>
					<font>-</font>
					<texturefocus colordiffuse="$INFO[Skin.String(OSDButtonsFocusColor)]">osd/OSDInfo.png</texturefocus>
                    <texturenofocus colordiffuse="$INFO[Skin.String(OSDButtonsColor)]">osd/OSDInfo.png</texturenofocus>
					<visible>!VideoPlayer.Content(livetv)</visible>
					<onclick>Skin.ToggleSetting(EnableOSDInfo)</onclick>
				</control>

So pushing that new button in the OSD toggles a skin setting?

<onclick>Skin.ToggleSetting(EnableOSDInfo)</onclick>

That is going to confuse a lot of folks I think (It did me :smiling_imp: ) - I thought it would just bring up the full info panel (not permanently change a skin setting).

Well at least I figured out what was going on!

**Comment by marcelveldt** [comment]
That setting indeed toggles the dhe display of the plot. To improve it, I've now changed it all a bit so the plot would also be visible in the OSD so you can see what's happening.
