### ISSUE TITLE
system info widget - new fanart suggestion

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#76]
suggestion for display, cpu and memory tiles:

http://i.imgur.com/ii8Vhqx.jpg
http://i.imgur.com/vEIycrr.jpg
http://i.imgur.com/CJgBqPb.jpg

![cpu](https://cloud.githubusercontent.com/assets/6510026/7908390/5db162c4-07f9-11e5-8863-62d00f1f5843.jpg)
![memory](https://cloud.githubusercontent.com/assets/6510026/7908389/5dafe250-07f9-11e5-82cd-b901c8959ee0.jpg)
![display](https://cloud.githubusercontent.com/assets/6510026/7908388/5dad1f84-07f9-11e5-992f-fc0b459296a1.jpg)

**Comment by mgonzales71** [comment]
wasn't sure where the widgets code is else I would have done a PR.

**Comment by marcelveldt** [comment]
I think you figured it out because I saw your PR ;-)

**Comment by mgonzales71** [comment]
yea - i was determined to find where it was hiding - in the most obvious place - i felt silly! :)
