### ISSUE TITLE
some text (button? list?) items don't display

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#80]
see screenshot of titan vs confluence
plugin is genesis (items in add on settings don't display)

I was thinking it was a default setting in the skin somewhere but not sure.

![2015-06-03_17-36-49](https://cloud.githubusercontent.com/assets/6510026/7974772/c503e87a-0a1a-11e5-9a4a-11a53699c1a6.png)
![2015-06-03_17-37-39](https://cloud.githubusercontent.com/assets/6510026/7974773/c6bf366a-0a1a-11e5-85b4-e35721b755d9.png)

**Comment by marcelveldt** [comment]
This is the problem I mentioned before that some elements can not be dynamically colored. I will revert these buttons to white color so it'll be fixed.

**Comment by mgonzales71** [comment]
yea - I guessed that might be the case - does setting a fallback fix this or do you need to hard code it to white, etc?

I read the thread - seems like it should work - odd that it does work but just not for certain controls.

**Comment by marcelveldt** [comment]
fallback doesn't work, needs to be hardcoded. For certain controls you simply cannot use $VAR or $INFO to set the color.

**Comment by mgonzales71** [comment]
i bet if you really wanted to hack something together you could use the helper script to make changes to the colors/defaults.xml file and then do a ReloadSkin() to have the changes take effect.
