### ISSUE TITLE
FR: add poster cases overlays

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/xbmc.skin.titan#83]
option to enable poster cases

**Comment by mgonzales71** [comment]
if you needed them - here are some case textures for overlay use 

https://onedrive.live.com/redir.aspx?cid=599da6bd82779e65&resid=599DA6BD82779E65!4627&parId=599DA6BD82779E65!4605&authkey=!ALh9Hs_pgf_uEN0&ithint=file%2czip

**Comment by marcelveldt** [comment]
first version added in 3.2.25
