### ISSUE TITLE
FR: Custom Busy Spinners & Color

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#84]
going to close to PR - moving discussion here.
will submit new PR with more and better spinner options :smile:

**Comment by marcelveldt** [comment]
Did you have a chance to test it ? Working like you expected ?

**Comment by mgonzales71** [comment]
yes - i like your implementation

just finished making some sets/images for the skin - about to test them to ensure they look OK before I do a PR.

I am most likely going to toss those ugly animated gifs you snagged from artic Z in the PR - :frowning: ... unless you just have to have them :confused:

**Comment by marcelveldt** [comment]
just toss them... they look afwull indeed but I needed some stuff to test with

**Comment by mgonzales71** [comment]
ok - getting ready to make my PR but have a few Q...
 
which way would be easiest to enable a static thumb in the left selection list for the folders?
a file in each folder called thumb.png? or can you look for a file named *01.png and use it if found?

i slightly increased the size of the busy spinner to 150x150 - the size you have is a tad small,

I tested using "none" as a color and it makes the busy spinner invisible - should we catch that or just ignore it and let the use figure it out?  i have found that using white with or without transparency via the Alpha(RGB) hex code works best for colored spinners.

**Comment by mgonzales71** [comment]
oh and you may want to also allow setting of the dim color - this is what it looks like when you use white as the color for a colored spinner..

![2015-06-06_09-59-37](https://cloud.githubusercontent.com/assets/6510026/8020576/e125de54-0c32-11e5-842a-671dc1aed9eb.png)

**Comment by mgonzales71** [comment]
i could see where someone may want no spinner but to pick a dim color for busy is another reason I suggest a color selection for dimming

**Comment by mgonzales71** [comment]
ok - created PR - https://github.com/marcelveldt/xbmc.skin.titan/pull/85 
woohoo! 

https://github.com/marcelveldt/xbmc.skin.titan/pull/85

**Comment by mgonzales71** [comment]
ok - added 2 more nice spinners to PR 

I will let you catch up now LOL

I am excited - hope the users like this feature :)

**Comment by mgonzales71** [comment]
think you can close this now if you happy with the selection of spinners :)

**Comment by marcelveldt** [comment]
really happy, thanks!
