### ISSUE TITLE
script.titanskin.helpers hanging, debug mode? restart?

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#90]
have noticed lately that the helper script is somehow getting itself in an odd state.

do we have the ability to enable debug mode on it?  
or
the ability to restart the script (nicely and forced)?

clues to the script being the issue (missing graphics usually provided by the script):

![2015-06-12_02-18-26](https://cloud.githubusercontent.com/assets/6510026/8127390/1ee4e880-10ab-11e5-846b-38ef5e287fc7.png)
![2015-06-12_02-19-59](https://cloud.githubusercontent.com/assets/6510026/8127391/1eecf714-10ab-11e5-9d71-c94b973b45b5.png)

**Comment by marcelveldt** [comment]
I'm currently performing a full rewrite of the helper script so hold on...

**Comment by mgonzales71** [comment]
oh wow - no problem...

**Comment by marcelveldt** [comment]
The new version of the helper is now on Git.

BTW: these issues you're having are not related to the helper script. Looks like the Kodi texture engine and/ore cache is broken. All images are missing.

If it would be the helper then you wouldn''t even have that dialog...

**Comment by mgonzales71** [comment]
ahhh ok - going to grab git copy and test the new helper :)

**Comment by mgonzales71** [comment]
Wow Marcel,

You weren't kidding about the performance improvements - even on my decently fast windows laptop it is noticeable.

So far so good!

I did have to restart the Kodi app after updating to the new helper script (from the old one) - none of the widgets, etc would display.

**Comment by mgonzales71** [comment]
follow up - have not had any issues so far with the re-write of the helper script.

**Comment by marcelveldt** [comment]
Yeah, if you install a new version of the helper you have to restart Kodi because the background service only loads at start.

I think the only issue with the rewrite is that there are reported some issues with extrafanart so I have to sort that one out.

**Comment by mgonzales71** [comment]
and i dont know if it is related but check out the issue I opened with a few strange things like collection flags on add-on video's, etc

**Comment by marcelveldt** [comment]
all seems to be working great with the helper service now so I'm gonna close this one

**Comment by mgonzales71** [comment]
i haven't seen any issues since the recent minor fixes other then being quicker :)
