### ISSUE TITLE
issues: watched "set" overlays and Add-ons, studio flag/imdb and music

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#94]
all movies in primewire and genesis (only 2 of the 3 ive tested so far) show movie set overlays.
salts is fine - no issues - even provides proper artwork for OSD playback, etc
music has overwritten text / imdb rating in bottom right corner

![2015-06-16_10-23-24](https://cloud.githubusercontent.com/assets/6510026/8190561/238de880-1418-11e5-9389-8d160d72bf8c.png)
![2015-06-16_10-24-12](https://cloud.githubusercontent.com/assets/6510026/8190560/238c946c-1418-11e5-87b2-3859fbf02435.jpg)
![2015-06-16_10-24-31](https://cloud.githubusercontent.com/assets/6510026/8190558/238a32da-1418-11e5-9e95-b84a5f40a161.jpg)
![2015-06-16_10-25-18](https://cloud.githubusercontent.com/assets/6510026/8190559/238c96e2-1418-11e5-800f-803aac8d6f6a.jpg)

**Comment by marcelveldt** [comment]
all is fixed. will upload a new beta later today.

**Comment by mgonzales71** [comment]
i have noticed most add-ons don't properly (not passed?) display studio logos - always see no logo available even for common studios that I know exist.

**Comment by mgonzales71** [comment]
I know that's not caused by you - just thinking out loud.... maybe one day kodi will support streams via add-ons equal to video / audio files - SALTS come close to making up for most of the missing metadata
