### ISSUE TITLE
change action deletes all shortcut preferences

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/xbmc.skin.titan#97]
change shortcut action deletes all properties... bug in skinshortcuts...

http://forum.kodi.tv/showthread.php?tid=201061&pid=2034048#pid2034048

**Comment by mgonzales71** [comment]
yikes!!  thankfully i have a daily backup at 4pm - saving the last 5 backups as they cycle

**Comment by marcelveldt** [comment]
fixed in new version of skin shortcuts
