### ISSUE TITLE
just a small cosmetic thing I noticed

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#99]
I don't recall this tab looking like that before - has it changed?

looks like the corners are eroded slightly - maybe rounded was the goal?

![2015-06-20_20-20-08](https://cloud.githubusercontent.com/assets/6510026/8270753/25f781bc-17a6-11e5-9b90-1973eca2b442.jpg)

**Comment by mgonzales71** [comment]
maybe use diffuse/banner.png or diffuse/wide.png instead?

**Comment by marcelveldt** [comment]
oh, in that case I forgot to set a border width on the texture. When using a border on the texture you're telling kodi not to scale the x number of pixels around the border. As you may have seen I use a very small texture called border.png for almost every aspect of the skin and just scaling that to the right sizes and coloring it. I have set the border to 5px so it won't scale the outer 5 pixels (so keep the corner radius) and only scale the inside. Will fix it.
